apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dizquetv
  namespace: flux-system
spec:
  suspend: true
  interval: 10m
  path: clusters/main/kubernetes/apps/media/dizquetv/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

