apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:LrfHG/9N3+wsJV8gRsLpYr2hqq2+fIFJ4Rj5jO6j/IX5fMDDSExy2E/m6xOtMPSal5/MAzGGlJuRxgOv/GVYan3F79RO2PtOcB9n/1chOnnnnpqxIOZ3WVgErTgqSOOCbcSyhoKtHASv15DQFVVSnOBnclfSjqmdOde2NHXWiwfk6XeKr5cEtU51/ubJyuIGiNrMqTy7rLIA9jgXH7POmNC9o0CyCK1JinHwO5L3iK/He7v4k5Re5pSdK4Lg22rmkenK9me+PZOWdeOxAlWNHunFhuca/mlcy+T+cgeMtmDtD0iugv2VqFJH4bJjRqxm+Kvq2pNCx517BB3SRDCgLc0wW+pdw/DyjhrkLTt+h+3JYpXBXz2K65ez8F1aILFb,iv:H2IYNKcoWH9w0B5IMOuBKsm+24dSDxMtC4tSBI7K+MI=,tag:OI7C31vjpr9yl0F5/RQyAg==,type:str]
    identity.pub: ENC[AES256_GCM,data:wPHbcJGBmbxWUvClatk6K0wgN83Jha9mjf9/aDvV8nrFgo39v0lay3P5qQaDpCyxdQChmYSIv89Zj+yApKTbdFEWIrrHc1OyBZB74NiDtlRlihBAb2/z3vtRGdcS4JbyZhn6IhtFgxH1sNEFCcg4H0GR5r4asYfv1/cOOnfsYlY8QVr4zpQaJNJBCII0mWixOa7Vo3KMyOXojXo10mSYYsUKPeG9ObTXeeV5rFCmGX1yiXe4j0fyI/z5zVv8HtxS4yN9xUuXZ6B9+RVxCw==,iv:uFyjCVBMRnrmDrUV85IQ+XYqiBIT1EJeTI+Y5NHIbdM=,tag:72pKBG8ZJMBXg4GIjqV6zA==,type:str]
    known_hosts: ENC[AES256_GCM,data:fy+qiSv7OY5iFErPGq3duRlJgW9oXhWWmpKr48qQy9HpCWiMxV8qMvtwqf78SXK0zhYF4E6NG/UKfYBY8pd32WTSgJZFdPJO3RnoIH7/54ysThnevkKdlyCzE0yVZMJc/jVst29zLi++AOjU/2TzMN2Yq8ebzICxiCJd9W06BFyTa4/chfaYJDqXvsoYQwRyXpv/2xL1CCT23a2oKKKdFA6MkQ/o4z7zlFBt,iv:kcUQ7FyK1AEUJzLUoLUCErMz+zSbSgTYrVJwWK467IY=,tag:CRzGO8kqzP//pHHSEy4uqg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUE44NklGWFZCTGc3VmVl
            V0dSck9xSnNTOVRzYmJmSDJQdW5IdDIxS1NNCldGMlhnZVdtOUhNOWdMZjl0VGgv
            NHZ0bEdZVUQ5eEdjYk1NNnNqTFMrWmMKLS0tIHJJSTNaUmd0TUpUNHFnaDVjbjU0
            bUNqb3czT045TTdHQ0lOcjRPdGgyWG8Ks6ZaHRN7Ndxlr+oewQZ9TuvcuIDjT2A1
            f4SP6uvHE/WGG/pRJ7PtivFqx124quRmqStIqZjpcNmMiRyY5hopAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T02:35:57Z"
    mac: ENC[AES256_GCM,data:WKAVLEksEw0ZIxJ0dclrEwBzAHwSaPcKePCKsSOju32a2eY04ofZ0beWt6CIYmRg+fwIGYJD6m1Nzz94tUyWEaNzzI7cFCQXIlc7kLFTkD+chrRpIaPYwnf9CDr8r3tEq7bcSxoa37f5qymxktiedpBMPuEP0nFCLWwZ395vZ9U=,iv:ddvU0pesTKQF7/QoS3+G1uiOpOUGKvtWnGAgeAMWkW0=,tag:FPYK7ZmRsOwJyM8s6Q15Eg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
