apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:g0MvizpmmQ0hqCZZCJAXL8DmN2jPquZcPjohkG/BCs3sMJM8bM6GQ/ZC8qLZ3R6A0QdFovHsN4qrYrrgxu+flP7ARC4JrI9e9IG1f/9SzDUri/YpJOxHYZaBgDqzkBG1Bnb6D8aeC8RZkhboLTAILx/a21T5IMssD/DFbl9POWIWMeHi6d8cofTprT45g9+Xfadijbq0ZQSsOMQ2dKkom4hMLcgO0L8KpR8aHDw8MYn96va6tVuHQiuXZyRikzBaOgIETFp4T+OW5mm+MWVTgYfOEhaDXce8F1XCOfE7j+w0+K/921xgPC4tq93QLtor7U7F3vcCCVvmRYyT4pDOuXx7AifGKXqLH7CkAoF81hTwHzRtyxf0MNijZf7smrRj,iv:ER24wDxPsXegBe733y5yH6wFZ8unLOObC57Rgm1+8IE=,tag:I176P571kfApMw6+6EQrKw==,type:str]
    identity.pub: ENC[AES256_GCM,data:9+Z4N3R/ckmZRmLBhZKdrBUNotsgKjb5eT0C1N3KHKQr8PJlEwbq9V2LMl6thILPBwS33kCyJlYQBs1TMa0Tg25/mxijH0fFTZHpptDQT2RnjH9iF8zMbSSjMXTfLT931zeh93GGuIuK36+iu5NxMXEB9WucwP4INQa6S3UzFijNYQxpNWcZGYziz5OGaFL/lkwCsZSrpMPn3tmSZW4B2Q3VB8+uknY6h5+3SvR4aEHJQm7aS3oQ7/4uNgGIXJgA04kKR+5u+I56qxALuQ==,iv:dNPwtomJfHhkaG+4p2hpKytVv60qaD4B2orFXvhjsbY=,tag:IfUvJjch0Yl/6zjvdLRVtA==,type:str]
    known_hosts: ENC[AES256_GCM,data:ci1/ij+qOq+HXbrf5e72EYcqpwvzRXs6OBLBGy4QYIwiU9zLRfXEVcZG4gg8KywNRhKgW3HD+GsYoR1koBYe986Meqz9w7tmQ4yGOeNhAGzi9MAwDrXIADyjfjtEAZo4PJob1b9bMlBUWiiliohIzLw0SLE2PtV7sYgb4iJHprVExgq7nr0XRWCgPijM97mdqEciTPR7ZKz+7YIH5b8VxzZUTKJNnTZRB87V,iv:QWNxVZEbxPiDr5phbfahUYxszo46fMF+sJgBBJVBRPc=,tag:oBdmA2mNAINlMWGCaqd68A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTitaaFZWSzEyUExHSW5m
            VzhzTTlnRHJxODByOVRxWXhvTjdJQXFTdjNjClNHZjhPZHUzUm9CTW11cXJSaGx4
            MENDVXVEREtpaHliTWhlNzdnM21iMm8KLS0tIFR4MkN2N3pBbU8rVm5xODgreWdQ
            Ylpva3JZUnZvbkQyQjdVWkRFcXBrWncKG4C6mFiC5AkADIaMy9fxHhgEr4YNcCS3
            NlF2digF20v/ozMcInxB2nRfdd5fxGVi/y+emITrgvor5yDyDkv5IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T20:29:06Z"
    mac: ENC[AES256_GCM,data:MdhO214Uj+8YBwV5Au7I3KR5+COFcgLcSn5FnmHq4j0Cie9X4lfSxDgJcn+25ryzPnkdm8Cf9/j8Kzv4ICa0YqnSYrIL9YOq9WPl77uz2tjAIYkwq42LA/tYg5wxF5meEpHYGehylxk2eWkYBS7cWg5wDbUMngUhWl759FlfnaM=,iv:XcObG/o7SH/gHmT3U1QU+2CWJroHeIfS6eTr4C8Lo7I=,tag:nIRjubvdOWYsGC2Jw1sizQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
