apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wEjt9fZgr6uUAmz7UGjsIJzos8bev+nNoLjV6V6nMmS+KlnCCK47DUAxlealTD7zjiBdCyr4o/7cPKH1mSjsQY4XmA4MA1ud/0H4lcxaMOgch42vNGDy4mgN5XwHxTk7jyFsBrKik+RtAz4+KaKg1b5P6F/Qglgu0QT4OdqqsSlg2ZZbZTA9UYYHegOB/+6cZiYVFiwEabIKauXAZCvW+xDpnrXqRNnhlR/hZmJNmYXmFmWRlXn71p1wJ0X5HvL5Xe9wkt5kO+n8gBaN2SFohKC4pc2Qc/X73QSu9N5Z0GP3DhcwCt5ChmTfKh3pHSerMNx11ZPIETmzLrNngn3Mbf6DAvvA6v1sIkPMGQZ9ROQrGf+U34Mu6k0pwZHIYqkN,iv:/EktwxnZgNqvhEwqawg8A7TQnQArnGZ3YRHBxq+oxmc=,tag:pam6UOrWfa84nvpV1YB4Dw==,type:str]
    identity.pub: ENC[AES256_GCM,data:VuuNrBrYZpjkp8SqqlgMaXF0IOlT++udqMf9kGwyGZgxFp3ZDWrFX6qeCqxosqKOS6L61SG9KU/4+BjigGMtweJiTWVDTVsb3Me4zWMe+EOwtGFOoUEGsd7YMMkUVshoR3lILnfYiNefheTS053cHwkRWkWudTqMVV2YMmNjN8EfQ3rTGNu8shu0BJ0F1ndOwKetKKb957U+81/e2WO8s3tQHwnctiaz+aBuVoFbrHkt4utSjd8pyvT0yn5X/jbOhIo8PifxU1DVgATerg==,iv:o163T+jdC/0LT4Ns5cNVwMvC96+7vYz60BrdiqE72Oc=,tag:qWksMz4CqCcha5Wr3Fnq1g==,type:str]
    known_hosts: ENC[AES256_GCM,data:vbMGbLHfeJagThvVuYMQalm96NHoKilDsEYzE+f7SqflUGz7IFxaxF1+/dIOVnppIgSilA3wJlBeo/E6i7ul+puATNX7WkblQmFFuSMPnv86mSitOVNpJ4oYYYpkbwPUmNeImHQbQl+y5f6EVNzsHtIB4GPSUi4C/FNv8DYbD1Z869ymvbB56WlLv0AMu3PY/3/GMLI+nTwsJ0aJj9706YDwMHikd5tTzPRC,iv:/r9a8pDSp7Y1oIXsE29vrO0hmtQ5da8cFAHD6yJQQ5w=,tag:GsmtPGJ/hhYa+7gJnhhkNQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcEVhaTNMYzBxUHNXMjd4
            dFRxMWh6cEtKcEJ5TWZkanRNU0NNeExRdFRZCnE4bkp1QWNXVEV6MlFJTUlPSDZl
            YURMWmszZUMwMWNqajVaY3dvMlhEVzAKLS0tIFg4akRYakNXUXlRdThQYkJwbUR1
            SjIrNXczTklFb1M5SXY4c2FGSVZGT2sKkLPazjDr1752GW0mhsJB1xX6d09yEpKY
            YK9lyPs8o7DOkrlUU0GbdzVKmVXw9dY5ln8uvuSqV49upSujZKxU1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T07:04:41Z"
    mac: ENC[AES256_GCM,data:9elQ4vh5u5VrJboa+N6lVRFAZJaNX2ZKwlgFrY1V8+4vG4Hh8KJOGl7pVib3i73V1plqIgRo/ZVmN/bhf9uaZhTox46VY4XXOVaFvM3TWcTgKXMC9B1InBrNRf3LduYp45Prxa+97qxJDBZMr/zsZB9ZhwXnjewtRs1I0lPaJ8U=,iv:cFQ4VzXxiCK9CTp4IHo26PpY+nafR5L7O2Tfg73Embs=,tag:Y1lmmpVWXMEA/3n7H0jz3A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
