apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:P1U6rQyeZnidNAC2dTTzG5Ou7q7Sdbgd6g7EnzxxHvrAL74G53anNKoUU5Sj2AKSURfQWcNF9DP8nwOUiilofPksCwG9U7ggRp4jY853o27GFngan5YtjUtNJlZM3/dTjTK5DDZEN616AtIpByXaW7ti7yQ10AAA3U9KN3kqqGD1xgPBG/rJm+6PKxFkmM/ZY2qw9XtvpJ4HtCqX5JFbvRJH427fU8RnTmFtqTRK1q08IU+klPJ0lPsZwDehhbeEQeDb6QuGJmwtv/HkPmqXT2NSjXonAVsWBncIw9PXp2gJNbehRWjqSaO55n/CwINmc32aqF3hFCvzvGp0oF/FL55UeRi5OunJ2E9yeF9S1d3T7BWP5h+K0L/yIRyVWBJb,iv:si0ruJEvitf6RvOvDv8cCs0ioFG1q77IALpRJlD9fWY=,tag:j5YTCfopAjQstoZ8HG72Eg==,type:str]
    identity.pub: ENC[AES256_GCM,data:ExGbAWTRlqxDmBjkz6xvL8y2IhUN84ug0TP5wa7wK8x3QG1yXnTWgfvd1pdxjmLpFe1UjpwXMq2CCU7hhPLf5gjVWouU0uJ3mlZlN7TNHFaojtDg3QrbTb1vk7MShZ7xwrwwplk2zhs+87UVFawjoPKm0kSj17ywbm6k8BvwttKmkDdda2+np4Cman/yT6C/qft0NMVwglfD3xVnPPKke5DGAgVRCDKc6OYYfnJeWf7fjeU/6ks0uFj+pcyWflxd9pEF3iKnsDhIPpHSuA==,iv:A78tsn/U9fhD6zRN2zLCUMeKpVry86RnHc6Do75mwj0=,tag:vRSRk99T1s2KPFMOLzsubg==,type:str]
    known_hosts: ENC[AES256_GCM,data:kVZtEDwaHr91SWTUL/zS3rvVIwFhRD8dYoOd+9prt9p5tzdtxSWW45ZwhvzT8Ru8qFoBEF9tYPm1EsnofMkLVU0URQ1NvTj1XSnfyEyMglZmaFmjAug5CIlVyiMjt6J/xqyEaksuNuLnOTqCQqsF3DdBD1jo9HM1zwKgeNVUPiLdwNqlTnGRiQwQxRW3imAxPlL3T2KDDR1M0yRHK2fs9LaSbaTiGBnn1eRC,iv:zxE/npxGp+efT9smqr7xXzeT++hBrnQqrnUxZnKrOnQ=,tag:P8Rm+YCp7KJjXECfb5Jesg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOXdPM2xtVi9XWWRKKzd5
            a0JLa3Z1blNZcDBYVVNibXZXaXRlOWptdlRRCmNnYUdBTDZ5UTA5M1UyV1NrbjB3
            UWtpYXA0M0tJUVNvejFHTUl0QW5UYzQKLS0tIHFBU2p6QkVmc21QM2dmRTFSaHBr
            K2F5VkoxQm55bUtlRFRPRFlaclQ0ckkKLdVrqidjp/2OxlS78bclDnjntmi9L8SV
            jy2fNHzUntXJRzElBfRVVcV3xRNAu+Ia1x3WEJQuUpWfLxLqx/N7PA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T08:39:06Z"
    mac: ENC[AES256_GCM,data:XasVfv/BgSDVEzAnDUjLHWMXhGlwf88Cf9+cmCY6E2WKvpgLy88huLO1YYsPWzb2gOIgFEUwUV5wPBeA+VN1argF5y3nuqVa5qVbiufiQX62hUdc4ZXX2KTMeB6rHj8aIfA39flfsWzx9mKmDH3LSyEDQsHAl/kvDiQpYyYwx7E=,iv:6MLlGTUyh9uxSXMGpeer3qa8ARBS1bVSnexdb28SGKY=,tag:7sXza1FyDKRsr/11jUkSyg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
