apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:QuJSA6UhL/+9y1hwGP/ew6teOk1rOzchH8QallFdHnbTp5XaPc+Guo/s7/4716ntTy0V9SXyobZM1ujPmsjpS1M2hDCp+G+aMH55+8tAQSwnGWhM4jMMAnarbV3Z55W9G4hAmvRb2dvbmMRUNAh0DfS8435QM+ggyWMApDz3JBBYyFvRnbdec23eVXZ7RdDAq1CayT4HR8nftlDDjNk/Jec1XKC36hS+5Up+ZhPNsAhY2cmRbUPMfNjSZHeLdDYNbUgkVPMMrGvyIsKa/jtgtxFklaRelsUzMPbwLzp7oG9WZ5Hjx9gmwMok/fWVLE3M2ul2uovMMx3r/3AilAbo1LeOtznsoJjbN7UYuKrnogLmXBVK/mwAH7wksnzd77bw,iv:nKEkQFLtlTcgTvUnae1a1cso26y/1ufmdRGNnVfjP9A=,tag:R78mgZ97JEx5auWGWsMxMg==,type:str]
    identity.pub: ENC[AES256_GCM,data:F0Xy7eyiV7W2NtK3DGIvl3kBPmaPoeEKVqfa/8jzEPZriGDeWezHF25bjfv9UQ3oLVxB1FLIct2pGOByF3jPdGsdBPcr4fmWuF/cYsEudXQuDeer2/e12GOxof6X+c0UmoVSsWX4fHMT/GQs5T2Sm03PCYsxHGrVp+SlFNkWwBKDmNSrbrhJ8LQ8i6vHm1+esLGxxhiT6zA8ZCqaSbbYWeBSW4LWzGtvF5hEHykMdIcHdulWlIceT99vBCHqc4f/8+LlBtEmJuHAPhK7mg==,iv:lYpOGxLL1DL6Bkw8Xp/9i6sFOBUKfKxJZeMVrpNP8J0=,tag:HNWmFrqirVEeD3eh9YuYqg==,type:str]
    known_hosts: ENC[AES256_GCM,data:KOPabcKjWn0Pnf8son0yfTZwZvptMO5L6JeIs1+oMPnHD18aish4bWrzxF2IJ60vrxZHQ6LWaOYW6d5iSX5R6fcM6JDxT16acAgo3D2567vGKOcQwacvb7a3pIPpE5KntEfvXt1gY4v1/+mPdpbwo/cXqK51kMTtOE1UR4RTDbY6oczKynLGhMWi8HVeqikIwTazBOW1cS47jb72vQmTUjZZ1jpLCOwRqmLR,iv:D/lcmLNAQq5CqaPh8HJYTR/VOFau0sY+BeXMgUVJ0Lo=,tag:8ZEe9Pz7f5dmbui0s/A/OQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3OXlhTU1GSFBhZ3ZRS0Jt
            eGNuTkxYUTFmMjNjYkVnd1RldFZxK3VmZFE0CjdqcjNtRVBTSFY5QThPd0xIVS9G
            enEvb0FIUTkwN1ZaYXJsbVlJRmZqVFUKLS0tIG1HaGVTdkFaWlc2bWhNZVZscXJL
            TG82RkRva1psMDdua1Y3cnY0OFlIZ1UKU0BWO+QHhNFQIepGFrlEtbSiGU2OH5pY
            g0vYc1c8KW0t1LYA9eFZ8jLf4UQYOqqD9EVYglUkUo2MhBZlaM4icw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T07:31:44Z"
    mac: ENC[AES256_GCM,data:DXp7zATzdCezHcJPmmz08G16KI8r96KRct/qJIMzq+30feLB3oUnZlzAf8HARZBC8lPZMB2XoZ0AgVcyQ0IzC31YFZfNH26soh/b6rF+mYlVngbZtHktNgSrr1CqptUty/dubCrlo9dumHhhvX16A0PD9lFoWJ+h60hSkpoANYQ=,iv:RUq0820gPVDh/ZA7rWtXFJ7sXTIoUO5ML3adu3FUyLc=,tag:r/D/ebxsf0hLMwn28S2fUw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
