apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:fUqx9kGV56o6SOyB5ocUxC7RMsn6n3gZ58GEfxzouVBN5SeFuochoHVQPJGgU5mvaoxCVDq9cLmmXHkvH4d7cOxx84/yr7xqQj0sMKcTrypI+zMjuC/FLTZz01L+gfNN3Inw92VQi3gRfSUXsA89vidtpZ+fRAxKRV3uQL4P/e5kgjdGQjxCZATRuK0qTTfNg45qczPxFuQii4CJ96sobu2ig8yrknwPBDFS6Av38THIn8Y4Y3Ttx8Jzh/lAiqNClFkLtdvaB2Q2MnfRrdw20ZR/0ODOCz6FpB/pTDUShPg9jO3sPaSDsR76Ww0y9/vJSb/s3vEJJCbV/JPYaj1qpYeJyNtbPp+HsI5nIEl3JJ7rac+VO9h8G3jKG/1h6IjJ,iv:gtsMCT9wt68vMwrepFzGxJFrDVHUUC1lZFOP35Ywu3I=,tag:bcE/jg/pr3lk6j64jJejHg==,type:str]
    identity.pub: ENC[AES256_GCM,data:ZxDASkkgmf4qo+A37U2bd4oBa9AMNlTWKsWR8kU1CfnZGN9qTu0nhVX/KJkcolswPdWe689GP7I7g6hv/clFvE//sFIqIp1/nbFb0tDtFywzO7ffl8aA0XTyyoUFJ5I3kIQ2EQi9m9dfaRtAGF+uL5nS1O9oDm69O14Utlh7q16a/JSPwMWMLI0HdqTpmXLT4FOlV58gjr3VWUD/qRhfCaGftNW7WU+aaJC7I/vnNtCIB/XUynuitRjJ4WI5/X5DZKv6lZRahR/aNX1l7g==,iv:bfihwSt5Uc1OsMRjU5ofybteDCuUKjkeUzc/bUDUgp0=,tag:RRVuFTn7B9bzf/dqxoiijQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:8wGSgv2eDofrLU1QeGxgv99ZrS16UT+gtMYe67x1GOP3OEVXUthCByRNPM9Mby13fCXC9NpMyDcFmRB6rkhkSohdY/w2v0lXZtmpL3XD12Z3ePZEWzVnv02XaA/TbuZE4FO8JzZR+CxyWq23xWmoC+QeAUrf+xwHLiUPw9fBS3HDpAedb2aWLAijz4BJg4iJMu1n4+1Mrket+dMAzLgSAApZGKW+3YfE60A9,iv:3LcYjE9Ugst6F0IoTPGi/YYiz7C+6vh2NNbJNT69MgY=,tag:nJelL1286m55Jsl/M33JJA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVVBvZ0FGVnRDOFVXd0dC
            bXBOWkJwTVVCQlcyLzBqaE9yWkhUUWVpS1FzCmlEb05RMkF1UHY4SW5nVm9PeEs2
            bFU3Sk5CdEpOWVBObjExVWNaWVJVazgKLS0tIEVtSFVXYXVkMHUrdGVGL3EwNDZC
            alpCb2JRazlrYytLWDZUT1Nkckd6dzAKzbdZbbrthF7tdNN/dOL8Zb1NzrrIMOpx
            LQzhNh0nlbUTXiTghu1jJV/v4xaR2buNCCqSlq1emkmJdcCN0n9Xrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T08:34:50Z"
    mac: ENC[AES256_GCM,data:FbpwoEsMrv8ywdly7t4ueUbo77lNiSH/P96x/x7l5prNRnLnjteu2Eenmz2FdbM6gykumd8n9tMeRxLQLcZI6FNTqk5jK1WdyWxFtrh1eQIivM3DyW/kOTKeUs33EJCqH3eIWpVefargpr9kq/lCnChN08GFJZzCHi+6JCKM3ik=,iv:rrVfdLbtkS970Etp5LOaZUMU6fbz46sWlN+LZ67zqos=,tag:0iwwCIR6xU5wDKog8n4rJw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
