apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:IDUg3TALcrlMJk6gFBueojfPYFSHaWwkvRgTD+plvHTTZfFu2PyWfXGbHXeMY6T37TeqRMICiCxpZ7AyeOayOz+rI/6EbZXq25e11SSDTqwhLLBPbkm1FZLx1j76CoXWIKqeBR9NTtmEq6RGNTshanePsdTlgP7FRLh/XYLkhvfABErjlMYo0NNxVrpkW63e8SjjFuNfu/FLJpO/+5Cz0G6kwPKdJMAPM43aYWMtbSQrh+lyWgTfPFq1DSe0y6pSB6EfLEn1R9GYXQY4qHJBR+B31XFwk+2ftdgYj6kBFevBvG1bPr+NjTN5FQ0EZ9rrmhpIvMeH0h3LBQFxjp9E0283g5P9nucVqvq+y+iduC3RsAARFjwWRG176LY3z++s,iv:V2xVS5dnq45l5Il6JQO6rrAzVt9HuSXVTsSKHxCvGrY=,tag:L8HQZbG3EkDTtHfmqOG31g==,type:str]
    identity.pub: ENC[AES256_GCM,data:SM51cgITQJ652I38sMVJmZw+vbZ5ZxFzPsb6ZgWiGl+TOWjYvCy/kHmZbiVAlHaVwVCBKQX2em3PP44JJFgH0ooHKgaGvf2wK0S5X4HrBSK7DbX5Ayws1wAAVcH/C3RX/BjOsfhB6ULEM0muRjYDfqtnjqi+lf4suIKFAvoR6khsSw/4+a0uyWBFx/FrYVkyjk1fp28eKLXpKoApLKUn95UkBHwbhS6x2+yb2o3ezquWCw2h+OWS8EaThyp4gyx/z4SfeYhKcJeunu/JhQ==,iv:qYWFLJ31SglKPZB//aLqAkME1guEgqRWO1yptIwK5ZA=,tag:vLXyROL6C4X20R1hF7ti7Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:bd1lYqA0yKrKDOEharSCrCaLCNaU0ju9Nel3lVEo5vJyYDSiLHuoTMJqEUjrtNV2C92hCYfeiGnvbObDU0L2nZfPaNI1nrZdsczKJlLwwshM1PAx+mhgb5ujktZ1IVuDV9kqmP9FcAKAl0G+dprbXTo7gI9uoWfLvybPy8Q0xZTDfaHB/BgzMn5jIfvw9cvWeLcgxaGdq0aZV1JlPfc2YutvD9U6TncARn0f,iv:IN07NvDhucexmyJRHRmll4qMpmBfaNt+uyvTaVC4+9c=,tag:NzbCTo+Yh89J5CGKb72zLg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnOUY4Tnp1UFZRdWFaZThD
            Q2ZzYVVydzVJRXh0ZU1NNlhYR3Ewd2ZlTkJBCjl3TFpId2wzd1BRLzhyRW9oYUdw
            ZUo0Zng5TW84TVpkNlJnZ2syYjJ6bTQKLS0tIDVHWlN2VHRxaGRVL1FnUmU5WGww
            TDc0Wm94d1FTbXgybi9XZ21mUm1MbEEKrBIkJ4ZN0t3qc00tU80e6NhUk0U8Z/Y0
            MqRR8hkOWGnOjOpex5BEqEx8s49+B2OnKlMyrpGrFQ2VQ+NJdTKgZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T07:05:44Z"
    mac: ENC[AES256_GCM,data:tPkoP197A+97v5w6131lwqhu+PJ+cDgNBhEVngcgyNFMTEzlKpQg3RK7CZeVEwd4fHm4GKmfnmMbAYjbarjpNF/tFhp7+EyLSpvYDvWGSo1Yt6jfo49oApDzV+6NHst/RRc8AZrTJuda583Sd9t6xrsjaVErNuZWAk/xgiUtfFo=,iv:NtkYr/e+5jf6ZlEMGhEAwulzr08D3/6mhae+vAAAMM4=,tag:uJxVyl615NUIHt+vQ6IKww==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
