apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:MRYIKV5Ex5hjXYCR1ee83syyMUpuZL2zDzMu6VkCHP3oqpEyz6e6M3OWYqWcBy0azyEkNYYa0EiPg6lwnIejNiHjZgt2D+3nGoTGr1qpNfBIivTeyAoSgAr8BrGFFY5FWyFrBTVJv/Fjfj82UlPNHg6jxS1mJ5nZumne6Qdgl9VNfmApGl+aH0+VBt5pVxvzK1GH8dof/30aJOMLffhBEkZ3tY3VfgA7Q7NtnIV69fToqLSwyuvzA9XwA/7NCIz96ZUxQ40jLz3gkYAUUj6EU6gYzHvmECK3I+tvA0W6NOgY404fE3rlDEEyBngV9ReY3OyxFfJU1krmxSxWiw//WvxEPsMuDB6jXlHePlNmoH0Ouy7OS6vK3AA3tEmV+fd+,iv:/jtLSelDZSFFM0bk/59wszlF/fSKvw/p4MUXFVlYNKQ=,tag:C8RVSvM4ZetsK7DTvptU0g==,type:str]
    identity.pub: ENC[AES256_GCM,data:DalH2PduQ8VsUnAcS+Iy9iGvYZTW/FFPi334njM+ii2OOYnrnvy6COs/2UOEIIz86HgKMg1NVLu9ilSO8OsvYG8LOEt9J3zrWMdA8E6s4rphpA+resiIDcszyh+8E6FJqCXa4sKa9UBSAcn2StZ8uxVRav1eESQKmlV5dfqazMW0ZCnh+BJsYdFoIGPgubShNOWzP2R9QT59yS0Wy0ktE/d2FzP3qf+7xPXtVtCejbmtVzYQX09zPk85xixDhd7uYOxIIdyl58pL6cc/4Q==,iv:gqlk5tpnWrhMpKinDKSxLt1FtBgZ0tMLEYL45zIeEk8=,tag:j403EXKIj8PJNLjDU0EI1w==,type:str]
    known_hosts: ENC[AES256_GCM,data:6gT7qZw0mGD53Y/p7TNggBD9o+qIKBO2WcNN7aGrDkxVF+w86DBsXvEsq9QcRjrpZkuKp4GA+5mZmcQkxcRICKi+2B79Ga0WTPm/7gDJ7FtnsilxoQlUH0/n8MyeC4zavRfbSvjQCQVKepB+ozJmykn3p+XDxAwc8D+BxSCnLGYnUvDv9S8QcMJBNCrhWMSBJ4l0X/ABWPGumRteD2BTLgo4N8Md7cYkibaN,iv:Zxz8+B+Ga1MRXyScHPUWx2FzIt2K/MwPBiZTXpVLUPU=,tag:XiqpQBBMHFQF8wXkNovbXQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcFRmQ2VkVVBWb2U5aGtq
            TGduNVNnZ040SENyRUlDSnNoakk3ZFcxSXlRCjYrZFpZUEdONnExbmNueDRMNjNu
            dmhDMXJYOHBuc09VbHVWbTBnY0xNczQKLS0tIFdrclJjcGNMNHc5Sm9zT3pjUnZO
            eldkN3FUcTZVNzkrVmdKaHMxK1hQbEkKF84JRqf4J/sQbjIGUtNA1G1fhV6DgN9h
            EMFPuUHQZHAuub6qfWwzjeGoN2JEfB6gKCe3g/SfJPxMKdfShoKhqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T22:35:07Z"
    mac: ENC[AES256_GCM,data:INCh0FU1NYC1jccYL9u6aDGNeGzdUEsx1f3UXTspNqImeg7jUNH60NMfEgLj3uxwR8O9rcuah2l2tejon73PzGF3HriUjll7ecMIpYaFo1VtMDwvHG9rhwd1y52kqOC2tuW0iOtkSdsX3FedO2W4hQTJ1FWPHZndYk5teDPMGH0=,iv:IHyjjT7XRWqgdF/mcSDKz+vnOr0D627AvAw3AcSJIpc=,tag:MgVTkF+nP6hPGC5YP/WHHA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
