apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Uo3XUyLB0omnwO7nqox7xAK25gHo7nGQvZyfmazhF9evymPXv5kZY6t3dQOcNvy1zbPJ4StAfpbawI+xXxMIY3SXYTurK6yOUm4xGzdfrlcXVgJ5zBlUyf6v+nbvQgZW56NLPGyIIBFNmU+3YUo2wn7mtCUO6PdkoSDK3qaTrCcV94LYdbJLYi09q5h0WYtA36cst+hsXTOX/AUtgQo3ZwGOSrvdUBYnsLqh9gMvp75B8/kh40qqgVnlEOuAXwodaniwHBEVEl8SRKxRZeS7soDawDcH6mlVPk/01e5DS+ngSFYyd8xX4PTJ5WOpUUdtviKMHxhqXV9r5ofGY8x0QSdm0G6XTwTyVGB6hOC90JQkG692CjYHNY3i+HUEHAg+,iv:9aPz9joYqNwZpJF9h2TX6ZNYh+7jzKDXICwsEBobDNc=,tag:gNc6GR2mtZjcisomHP8iCg==,type:str]
    identity.pub: ENC[AES256_GCM,data:gSM/Z/h+UfzkRMYUQu4on5WayXyWJ04yMWyOtm8aVMKItlMJ+vvzevoMglTZvepOxGfkgGuzONAoE9P0A8k1lOT1haIN3gbciZlu7T8MBOyC+o5FQGEe/gqoIcSOM+JFUV//FHPuaRr+MelycFWqW25EXUdObT5FzrL2A7nLXKjbett/nuQ3taQNceLqEHfrythIMkpvlxMkZOZIHYN1HCydCZc1w31iwq1055zQ5BQJQh204JY7i86AzN5DUwaU4R32QT2bVPQE12cOqA==,iv:hKrEckzkihfDQwHaxzpcMKmmLetZF1JMjRTKInLMzI8=,tag:MdUp37WtcmHOik+3KHB4hQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:dCO6wtlI+O0ndMYOUl1n6hCeWm2+iZj6+qUqrEEyY2fOJ8QERGbvLsvor4rQ1Kroiwik3NAl3IDHjjHHA0SQnbXiozxdkqciQkS8OeAMr/+fGPc2ResF83KtouxXHWOqQqX6zL7AM+OMbH7xbJfbFwvseYgPIgNg5urEU/TP0zIBoGthd2RI4Y1IO/E2GvZkkx2O39Hzm6QfyYnhMzQBoGnKrK7gN24pdF0v,iv:5HUOzINZNvbmA7BvOfkW2qu/krf24NWBK2dUWMNOL7I=,tag:uCV4wX3JdROSWWAohxc1hw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UHVlZXFkUXVvV0NEdnFC
            VjhqZ1RJVUN5bndMbHpzTUVqQmp4TnJsa3prCkxmTDdDRjdWOUQ5Q25GWHQvaUdX
            aTNwbXpKeTJUbG5Fc2xQWnZBRysyN1UKLS0tIHFzZWFKSFNaNWppeC9JeVlKL1NP
            WEtKNkpKZVRMWHNETFRobW8yOE53bDgKXFy/Qia3V5crA5hQHcdFO5mh9S+hs18p
            O3UPs8+ekgr0C3Z99OIgQ2hJCFBZh1y7oN93S9b3gG1E30ysUqQf8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T07:07:26Z"
    mac: ENC[AES256_GCM,data:O6o0jCUrJe4Kwoa/aMnytFLcdjc3aTNEK7gwNfaaMOiOPMy5X/kILHXIMp44NCUWLRlXU8gi8FqcIB2ai+CmgTjcGYr3d0vdwqe0kVRx01cHOQIJgkRnTdREMc0NtNR6LN1RnscOAwlpDHm4TJ1wtKbwR/93LFF76hCxX7KzcSo=,iv:yzw2yEk7z+DHJiOQpo51ax/L3TMu3ZnV2uEIvqfrrMY=,tag:yuuGl4Pwd77cdTwuHvWNtw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
