apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:TWxsLtZGJUh0zv04rO+IbileWxyo/CAy77mW96TYecnBAZghLYn+XyXtxvv4xyltC4P4lRkEywoPPf7wsHzf/cejSKfDdq3ZgvhHVSgch+kvu3LQNeZDPf8qfpOXml7waMHLs8+n4SxQ9BQAEOS1xPHxFjCsdwv0ms2qhUtbk+9TrU61ya+IGxAzUXzP1E9oKeBGbiW4Ed07DWLmHFwcxjXPCuiHxKe61sRC943aupDk8lYPGBPpmmkWwHv6wPNquO4iwtmBRzMWK6XKJyEADVwSTkUVGEy1t1PK6uwTF8ElbapNoha6JOgF1kdyr1/hetWQrUvtqom4/CB2a2Co2JndahuS5eLdE0Eyt846JWopySgL6bMzJDCLHDi6xFkx,iv:sY2Z8jOuOE+QTTzYB+r6u+WV897hT6tVJmS9b0phF8k=,tag:svUk36Z58XdOIKgzlfSM3w==,type:str]
    identity.pub: ENC[AES256_GCM,data:MUS3SmQSR15ztyzGmMu7in/ULg9PkCt0v76P/yTzekABoaP1QX7IEI0BXM8z5/IjP+2A3T2DvnrjEDIu1IfdTWmrHvp1s8wY+VGQOx4UnWYn0kVwjp8l9XaH+hWPw5j0rBDiySjMcN80j+SEs9eJ3pE9MdWoGcKJvd/sY+CHra3tKyv/FcD5GiRSPI3bxAIk93Kkqn6iS3Fki4IHikoWGZebEUsS5nIH7czDfRP4+ws1O1VT0hqeC62QRl5YSSFr6kCCe0BS7wc1TX9B0g==,iv:bXvvht2Krf8VydQJWdox6d3rolDUaq9lAcXQWuoH6SE=,tag:sonq5AOqZY5sYboJb4xuFQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:Ggp+YItCkTNwLTAFg7rVgbsPjB1YNKNOfQdjQeUQbHRbhS04ibLAtdOqSZlGoio3kZUvxn85vnz1+7tWn4JiPJ3aGxgd66qhrGuiCtUoJLQEhDHQyaxVAgjfQHh83uSNV/YhGuhvINkcJVa8ROOQhTBpe8GJDBvi01g8ZXOSh4ZuoAlUDPJ00uRhDk9CmuYTKcNxpGyBPB5qczTbnSyR6h7DSZBvsgtfQHgP,iv:3yPx3SfoHbJmvHu56by+K66US+6YCcASgAOv7b5HXcM=,tag:L2MlSj0y8k+LagUNFCbixw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaFBYRmFPdDg1V1NGM1NZ
            eWFFZ2tXMTFObko5MmJEd0hmb2Z1N2tlbDNrCk5KK3lnemJJblBna0Q0Z2puNlh5
            K3BvVGhYaHpFOXFETjlnSnVoWWtBelUKLS0tIG01SC81ZFpUTnNDaVBsV2MvK3R1
            blBIVC84OS9HeUYxQ2x6am50RUZqMDQKSzj3M/aNNTp5zOwtNGLYXVaL2Fieqbzt
            FYimCPH3GqjnDc6VtM26QaYW3eJq2SIXaeCyozzYJbPtxiBAEAewBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T22:22:43Z"
    mac: ENC[AES256_GCM,data:uTz1DKY1vKc0qCNTnHClOqlGJeSlmxqGRCpmsDMjBA3dWzKDaZwzfrvWONBmrhs7U9TEPTSPFg8zFWGakL/O71jPndmIPbhYhbB0jgdHCd/nSLLoj+ThCCUrkMjClti0k0s4eNd9sHNVhXXzK1BUVF6F8/u5N4DTToEi6IL5pEg=,iv:Ky0Sl/u8U729UCgR6QSQsxbys1soi8xkiNEUgtpYSZ8=,tag:4BQX58agifpf1xUK9rJKZw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
