apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:1E7YMmZM6qX26Pb5I5r3KfDVpF9+DOS755PtkUEv2U0gh9/E50pY4J/FA7G5LT+B5yA67ItPwB0k7QsurPsvuytUwibWWMIeb0ndFk4ecDLtF6plA+KyOLULaBTmkOdkHhbU7U12NNVYv4woJB8L3tqKiDu7t0TvQUaHS2AdqtINKTTN5IyziJrFWFQhVHf3tgKIiP2lN587GVqsTMW9Fv/oEIEn8NSUfQlUizLhezWzYW0j6/x7dWqnBFFhGAzABMwNrmCTTwiEXXbFgx4cFgVaiGgA/iWx18m7ZooxghkvIiw15JVXNw5237DF+tXfNSZu+OjuAbu3zEHJb3C9dtMiaaAr9W0ALBZuW3TiWQNmN5trJQaYIijV1u9y9D6l,iv:awH76DxwKoRzBv7JObFpI//0/bTFWpbcv42E0a5VLBs=,tag:YUIJUY+KjWTzdisi6YjgKQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:tGHEbxMfKknc49YwPkNH59m6VwrEUAD5UiEKTAafo904VtWYDpowTNjzz9YtLkmZGf0Fty/cXk34fhMPxw7fBeJZMntoiblgSODXJxco4UHXn4r8qmLZfCca2UPSBb1a/tYhDo90AemF4sYT8MkJ1DaGrvMiG0Y+yLpshEfZNlks/AImdmgp/SvGmtF8DCgOm3mVVxofPL6DXwe6J+ZvULzMsq/6xfZcNCHhclrSTBNcSfVjTmLN3jvKXr6addMDWbt+dOGwfjaOJMLq7Q==,iv:/7lNd0pRMfkSenOYa3BMwIEW4NU1uwoEk6afEg3anOY=,tag:PvChy06M3kp+LDdoQaBAvQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:BB4KPI+HAN4dYxm5D714aiQ3pgdVGIq3cqDy3Rjj9529sGdlTH+NHJynMCcerFUgLTJlYFX7764vje13MNopaFkrS5w6Z4wJ2tKgDYa5VzEjitjuaGFUiUgaaESmFioO4RdAUnnPFIU/VtSG9SzAsrHLTlDkWD4kFgNYVixFu9CUHDilDiQOhhJuEmD3t2QwaotxWI3F1FVPhJE+rj8KddrqgLR69IHaHUG6,iv:u9SDCV0a9B5hQkPFWvXxm9vpc+GJbqpyk+UqoPDP22s=,tag:1IcIMjYlRIk2LyDh3x4Ung==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHem1ncU01U3Z2YWo0WWdG
            K3pldmVaaHBnT2srZ0RDaktuQUFaTFVjMzAwCklBZFhXRjE4YkdkczdOclhFZzdy
            L3hoRTdTRGlTc0F5OE9QSjd3OWdadnMKLS0tIDRpSGpVTUQweGZyQjNyakxwazVJ
            NmRHM016NE5GTUQ3c0dURmNaWWtOcEUKCRTfZZAoyo9k+AYhQdQfEQhV8hG1KOir
            Nsd5cVIJGvUlEU49TnhzOf9HHLkdciAnJqm+iKr2c/Mi9QRfDMM4Yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T22:11:40Z"
    mac: ENC[AES256_GCM,data:PkNqUI75499KGusH1ofbmhR8FXoP42a7PgndUHF3D/6Y3Sh6LBI7FsJ9WG2cfISGkHxtKUWxVEcXgXKeY+cFVZa/9+TLAEaZ6yL32m2mo+/rn9LIUyS62Y32O/0ZIjgl5/Ng5a0+Yy5tSJi4ubHWF4J5/evzwXMeDGoJCvSQHvs=,iv:2VDUKBICdmF3RA0dGyU5m0xjZA2gizUBTNIUoouOqGk=,tag:HwnJwcu6xaJOGcqQiuXfzA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
