apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:bxLUHI9D25rKX4slq0Vlfay2m5sLJDhaZRPxckSss8VF9gojQckcWI04cj1Vae5vRicfOucAjnKYT/zxtU5Tp9doTJZftQtHqzK09EKizvhOIf2aZ/2/zdfnAc6V9coJVfRjMRttcxkfDUfmCRvBtzLuhggccu+QV7+JM5Ja5cOg/RcpXkO68AtrJb7sx8CTSBEgrk4iirutqdMEsGmyWF+9P64XYLbeAE02I+4UshHXHDp3yrFWc1jcVm4Mdh0Ct75d2f+DoCYeIKv588ogn8D07rBqdAyz1s8l1/7T3Quq/Stqcq/DWFZH5IV2gMRou9D8fQSZjsIdvzBZyOlnpzbH4N/fw1gkG3Fk/4ehFxcc40WR7Gx1Oae5Sj23EDhy,iv:fLWJMTidsthMH0TchVaU+wvF1ldRV4sh3iNZfvrJK/s=,tag:OYPi36eum1THaLGPjnkvkQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:gno5tnqM1qLdg1CKpF1z0lC4I7vR7xzx7FUP5/WX8uDLZHDkrFh5hSEpNU4t+DSQtVUFMLr3M0gOAyrVFenWhYwW/7vUMGp2gvzPLlriIUwbTuo5DMR2HiTXDlUCTzUQUV/jGJ7svB7HpzgFnvTPiVBslilwkf1oAm3VoSQYmpCXG65SdplPweA6qdF/AtNSvt30FwHef5+0D8WgK8vlmjVUhBDVMU664rAZS8z5SWPkfnhnHW9aR5NE8O5qRrhSSmi4y2qu40Ng0yvvsQ==,iv:MVsZMzBg9d6wLWyT6aaMI+GlYC1/WuosQPdqjfTekVE=,tag:1wiRTLkYgmCVuD3vItLqOg==,type:str]
    known_hosts: ENC[AES256_GCM,data:Bt/0yBEeQqXTdCNkie6nJXwyWMcE8Bb05L4gtGSZZzv+zu3QPGUnlFq2YKFEQTaWLLDmfQGvpRoU8T8jTUntYLfqcvun1vR2x6jDiA4mUQdlSCNGyWwWgsmlwADa0zqiArfuCDjvSDM0ms3ZeF452WPAdpkQOPEQ+NznOKYwN689z4/8zK0v/gjbeOa6aNVQuHPnWn2mwE8vKlPXaVjXAXo4mJy6M0t9vBsx,iv:JgXZt417sNEpSFOhjkVe2rjQMYEsP18ltjHXAoyofJA=,tag:CPmrFyv9Rn82mKgHN51SGA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUFRERjVIdXU3V3dUcXJS
            SktmcWVDcGNHMHN6NktCOGg4Rkg4ZFREN25NCjdmRFVsakE5MDdXN1ZtVmNXRWN5
            YmdPcjhUWWpBRVlNOHprUVhIcFprV1kKLS0tIFFxT3lrdm9pREJ2OVRLQ3k4Z2F3
            SEZERkpReU9jbWUwSkVWQUZnVU1zZjgKKYpcSTOc8XgOFKkHaVQ1PBt8XaXg0WSZ
            Qy/CRmMY2tHxKfe9N01ZRNIn86f6BOULFc88awfMJ52fk8Lr+CTH1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T03:48:25Z"
    mac: ENC[AES256_GCM,data:iFA47Yq7kUNCWlxiLSDXL/fZyFbRmZutiWD8Wx+akdCQBI00TuTuKokvw/+lR/Q3bTrgYA4JczDW0jFIvlVeixzK6GQjzA33FJj9qCJdTsGB6SH2vQjXWui7ER4a3e9x13mUtEU7rTUXQmXd8Aook3XCjTu2dijKP+FhjhD9elc=,iv:Z8ClgEcv9CqVAy4xXy9aalwyKbUz5m0t3PE37gU3NgE=,tag:GqV+zpM+oILsm/jMopvFWw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
