apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:yRvbeOCpFH57PNAUXOlbLROOvlKVROC2XU/FyZkqbmOzPQDcN/6rI9ocyzYU0QTMycn9jkYIbV9Cl3X5RXUQ71/++LYF/G5MuCbmoRBqy8rZevmwq5u7mkc9zaCiJln5UY/IceU2ACC45yauOctUb+SdGeUbDbWw+U2agS5TGGF/IJQpNDO7bgn5nTfPLZdXEiMHA6KZwQ6ktzxSIfMphywTYR39W9c7pId+6x4r73ZCLd9koA2Qwi4pSLZEmFaDeiIeRokRiB7al6fDTUkXpJ+T0PKiQ4pDmGJDwBOVdprCWN0grVMVoxcwP7+ofa88liUN6L7QPFY2Leunp2I4NDMJ3271iR1599IYPlRw1vRFv9u8XYT5CFhWgHXghMPB,iv:SeIw4uQJJD5G9XZ+gwc1OyOVoYJIQpRNhNvCKu++bKo=,tag:NBHyqWom/f6yDMQiXwvBPg==,type:str]
    identity.pub: ENC[AES256_GCM,data:yIiqWCAQKpIyChCECPxl3jE8wQupVft5ORNwQHTWOJIOdN42qcd6cT3sZNVJYWl8jEjvCGevFjOvR/rWc+lw9QV0yKfAakvBLLJxugUwmPYEGWoii8JeNgEBlRlWzcdOOknrTDj9GVh8yWFxr/no1eGixZ8cEOLa2EljBOdNNyblrjVk0vlIZDJ8CBHW4ecwLE0mrmtmEmdEsJd59DZac0myxjLmxnfVOKFhGWlcTP4xIGhQpMxIwScQrRSF9csoijha/EwtcmQg/c92ng==,iv:EmQZZV5TlTrTwb1BMQ+oUzWO0xf2WRN7teqxrvR/qs8=,tag:uIBwZQ5w7GZYRia0gnb3UA==,type:str]
    known_hosts: ENC[AES256_GCM,data:K/CS824RfN+RmvOX4iCgSh1+gpk/E2h3UA2efQllAqby6cKXyoFc7CziwAD2lR4UgZVQbHf/z3Q3gxjcfUNx+IgnB+VDRjb5o6mS08SYk970LcVNQwGhU97ok7h7fI7VFYyobnC5nxnXM4IXXEG9E+fZhm6xq9a/UE8Y6rVA9nn6uCqLhh+8IVNxon7LUFn8Vu9ioLng4p+MOFYMKjtlagPZwkRpB8voybLn,iv:TafChpCcisyfDZJ8XWM45ZwYVHGiOWwc1rsDOnMU468=,tag:yc0ZkvvH5MOZSZDLVj9T5A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TzYxV3FBNVFGNGd4OCtE
            WWlpS0VTZkpRNVNkZGppdUt2QWlka1lCYjFFCnBkWWNYMURLWVpwWDVkbjhWVDhq
            UHBiMjhvRkExLzB1UEdoRUw5ODhFRWcKLS0tIDBSb3dCWW1GUzZyMjdYSnArbkpS
            djVHbmdIV1BWWC9MUVUvYlZvWGZQWTAKtb9X2axFTStKH7Lw/UN9/OTFgsXZNuD5
            kNQSpilSOcY7hDC3d4Hc26Zs4+Vr5GB2lQSuDYks4NW/vtGEz+eQSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T19:20:19Z"
    mac: ENC[AES256_GCM,data:B6gm3JOFi27CUmmHJcIuslstzVpCugGaDttjhvA+tSAHtLkDXIDeCC0lDg+AHS8rl4NDiaR1tP+nJQYL8Nr1OK9tdBT9hIJ0vXwcDyv1VOOmLLiCioM2g9Fau8aCfGsSVpN4zdMCgsGGKxQ0a9G2XvPuQ0L+vxlGXnSr5KGLntQ=,iv:SWM+cWdJ2MYmnwJvWHuTNUwbksgJX0+3d/s3demeyKo=,tag:AcbklSVHGZ/chV9wi+cpug==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
