apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vbSbMdjMG9s1aZUxG7T7In1198FB3mZWYX5DxFmFaWRqok+Wg/0tk6+0iSkzywzFVFSyOMM3RhLSmmo1Bk1n9aTYnfPgQNQ3KpBye3EsClNm04mChJVVgHh2oKqln39wgDmJHOOTvHrq9e4bKozjHFv4bl46wAyu4UYlDzTGkazoZLZ+yhImWJFagCA29cadHrjaRLwYgHIH8xsUhHWsEeoWQrvP71Zc8jSXHkJV+pK4THdfGZEdjTGioddvnxmf5GPrxQ+1Rw4ODjUoFpMtbBz/aGu2lserNxttusjQcl7mV25fsiy0Vq8v23bZ9f1bDrmtZ17hoVblsBWGvpu9f6Ma6x9MpYkZNHHJP1NdAqjDkGKjJqkkkt8ireRa3FvZ,iv:t4YxqAVOv5r1gLta1eM2qW/WkQt8k/5Owtfc6pu5MRU=,tag:qNKH4wVc9SAjTLMub9TbRg==,type:str]
    identity.pub: ENC[AES256_GCM,data:7kX3ebpNl99OE070ukaPeRWB6PgUbrTgMjky6rl47ZjFMa8noB0oq10RhAQQNkIBNocPIV8TAk7BnCjZpIRjo8wPsFdvqZHWFFiBZGNtODRFPXHsQnkOdR++Bsyr7gHuxBX0WHy5BbeSk7IdVNN0L1jMZsv50Bcgm0zvpiUvKE568Bto1KeHOiIbrIhaEab+37R9FIkYFUcXn76O/GwuNCmPBFs0pHI5XnIB5DfHdEI7J+jeYt3R/1viZq28Snl9iJBLMgjubt0kuS66Vw==,iv:/KE0WiVew7I6oeuiR9JSo6XJrktuD44bJi96QaiyFoU=,tag:MDbOXAtvXHYRnLGrJsq/aQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:Jvyb4tCQyIAQijUVfM/xNnt9l6YXfwXoGIVhm+OqrqnklVHkeAh7J/terH4EsZttGcMpwjPBz+ZUmUADTd+hcaTNiczigQekQWKXIe2KqHq5OoFzt+rpu3f+86FH4bJPShe6hX6OERqVbS5AmsVolyOpRlVdZwj97aOgcg0vHq5FDkT9DmpyEdwv+gJSAY7cRW1prCSIrBKFKA6WJ8uYkQdQ7TjDUpxMj+6C,iv:u8eMeNqWqFGRnn4davJuDg2PPHIqaBFoaesBAd/oRYQ=,tag:ti3+vyTDKqd/HqYBH0udSQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUnM1RWI4bVJnTjhveTQv
            Y2hjekxXeFpOWlNmUjVwMDFaRHY1VDFuK2t3CnVacHpjbmtKUWxzeDNwYTRzT0xN
            K3piUE5qWFYwZGVnbklKMmNIQTdiSDQKLS0tIERvL0RXTytKbVJLUmExWDBnVWdv
            WDlBbFJRdkU4Y01oN0FydHZYUUIrbzgKvRh55iBzOMUaPP8Y4Wzh6mVTCFiIfXMA
            z/dlHoKiUARm+9EkdA2ZbSQ+Z/E03BQFez6yJLSRoAvmcaZsyIPCrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T18:01:17Z"
    mac: ENC[AES256_GCM,data:kShXJrEizETtG1W8hiy1HTLvE5w14OAl4LHPDyftT0M/e4FnvdL3Z/65euenFBF3C49U9+SZdVImK7RtUGQ8sPNB7fgqaze1XCnYFdsbkW4MQSGBAOB3iyMofA2D6Poy18bWy49rqFZEB6ldkHWo9uSxsHfMFJiAOQtQZ6VICtA=,iv:Q2H/gZtDnu5tpJQG2yuyKewsTLPRrCuXbgl+lsvct9A=,tag:qt+l4z357xaASqKaeg/9dA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
