apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:gdRCFtsbHg8MAx38FQd547gLOQrmfGudbH58b4lNGU9bqarLecCO9F+iChVrke6A15BBLlEsJp4MCbe+yBVFh7QmyOEs9K8z3RoQhinixlASnqq6d674u4M6gYE3XXQhJ1JpffSu3OGVyUIlH0O5rL4Z42dO4M8UWb06cikhAz3/CGIyIYWk0MkVZbrPa58G6JGYAqBY60+stsI6b2LYeZ1c7cKTF/5j7+SOLmnQXQBck5cxgTMKfeux2HAkwcQE/ex3M81SPPNO/mK56P5v815GuPm+xi5UT6cV+e00NVsjJLlYyB+hfwr/GNhOYEfnIj5Kbtpy5fI8kVm1cW/LeM+vXKQAvas5pOLu3poWSeKgAOJWk4fRvzkjAEz6mO5Z,iv:G52f91JSv0WhXNn+jH+8whuUoLZ6umFa9dMSXW5wl3c=,tag:pgANtS1fIZHAMIHBCbsb3Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:dDCOVDIv929QG3J9LxkXhuwK8et/6cwsuIEIOdU6kWlzQDSmwybfXG/KhHssT4aJxjH8abCJGhu/Us5opwDUXv1nOuWPbygMQKcS4AwUIIDoILmgCUS6O225cperh2KMgTersVtMKPnUREkNO35+CYiGLnZN6jt25uWGi44/Y7V3m/oz7y8UvKwhlqW+SK7xUElE+C4uDUuCHQn+jMBs7Llz0RRBzYmaAv83smvMpji8qAiO3A5RemCjyxnvTJiw6dIthYQIUNZfnYOnZg==,iv:r1HGxEVdVcPbb82jsryl5gRGdlZkgudrim+f5OCReMs=,tag:M9OxibIQwHEx/yuFFUaO8w==,type:str]
    known_hosts: ENC[AES256_GCM,data:b9v5xYPZUKkOMUULGwOpr7zQmN7c30IB/QHkscW6YfYbIbLSSwF9IhiUUMtpYHssjfHCDLqo+55s9MZiAI5FyNtf4C73AMra2IV+o5hugkIFbgmDoUTPdjgGRlxNAW4HBycTzt6m34oFnDq6ewPMlKLH6xuUadJZsZge1rKmhuPBMs6hbJGYCFvDnSDgAgm9w7R0LmPrygId5bzMfDVh8Acv7HM/esp9PB5H,iv:sLUCE4JZvD5F1ldZCeDsRzeZKrDWTXyqQ6ag5SuxOKk=,tag:ZTCWgF+HoKe45KtRT9F9cw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRGtwZThsT2oxYks4WWJo
            UTRYTGxNS0FrMVN0UERaYUtKTnRWMjRSdVQ0CkFVSno0Zjc4aVpYWVo0OHdDYTVv
            RWQvelFGYXkrUlhRNVVoc3lVODJSTEkKLS0tIDJ0eWZRUDlMRzNlVEJmeHFNcG9P
            bjFPNWNHTnJ5V3hUMTJodlVxNWJidFUKzZxiK8uYp8WN7VvLlUdzUMtBfN21I8PT
            G6QiLxwdBP3zBjBOB9es9/bxxUXMTwx/CaFr/Pl0ZW3lk3RTtSNkjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T02:18:02Z"
    mac: ENC[AES256_GCM,data:2ipdMMikzXVjRg/rcw3f6zzdRm+Au9Cck2qkAuPvbmwE+j+ZbBs/jxv3dyZu9ef9VB4ovylNY/n64hXNzf551diLpvxL03cVK0WKlqgPzSS9T7QeC9tleGysFoHGsZOT7MadDw+BRvR1FP0dnxujmBSlDMQqtRVteSQUX1nrU7o=,iv:9LICFXlRw2vKQ2YucRQQZKk89WAm81QVhNIX9iejGfE=,tag:ozKCuCmCmre4/lMb9/uCXw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
