apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:KPqpjl7lHBJiUnPG1RvcI7E6nM11SdBQ67GYpU8SkkPvzxDXMKS4firrypmhZ72nOdXJkQim4/ia9i8wJG0vUKAgxLexUi9XdLLQAT06m2UbXDz4f6lUbnIlxHk15j58vIi9RZBDZAqHQ5Pzxj8DKEN6Y8awwsndWYMIZ2MQHpLd0Z+KifpzA4WS+ToTjJUGvcixBjMsGiVFA+2o/kAgcaq2Ehl+vYprcd9lb6uLgWgH3i+Zn5MpsTe25xqM8rz+jvORwMAMKaCQeIVPwsk337axQF3Z2TJNefXEfSreLlJlSaI/9JTMMKMeKZMp+OZ4uXwAkiUsibB/2dC/LvGfFyCnHuLWW6E/U585BIIRNKc2aRoqtrpdTu1cEE4pFjVq,iv:PwUCUlj/hTcGGnkCRiL4lXvsD0qJKFj+WuE9f2zojzo=,tag:oIE3hHRZkI1mgetvJwW69Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:osTqhvJwcEHVUuW02+M5g1Yy83ZMFo5p3oi3H5L6nqasGwmTzlCuPtlsUtSz1NSUTiFsxvkBJyoVKEiRkcmSLQElQBqksLVNdDZ1T/FrU9nKC40WNd0dRMAqQAQdh/ZnfnMyrttvVzbq8svzBdOwAtUtE/yWOMGZ6F+JGnmtZPPSPHdBUxAWEbfArHpQOXmdRzXchPA5fX+xR938Ew/AthJXsJrF982VTY8Fav6I4XNdrv476rs119YrlOrVGxAL+V2X3+DhiPhjeqmjBw==,iv:tJG1/UaGhTEYQZgJFeVJIKZ7mw7lEZp0/UrtSmL+acU=,tag:vRdC5ghiMPW/k4Mjk7OQHw==,type:str]
    known_hosts: ENC[AES256_GCM,data:r7WIe9LjjdoA4hrmNJxIeNJCpdLCwoJtg6SFIQEspvzA87FWXIvGK1iWh6r5MF7C/WXLKWeOSH1+tXE9Qoj9/TShSAtB8vCuGVvJUpBpXiRNMm6k/Jq22fthSVbl9lzxreSuQSBLyHEqRWBTe24D5Iu/7dJNMQHxYDVgeATmYpb0eFGsckxoU+l6gyiVGn0lLRBma/tyX+l25iKkbJWcQsBz6xs2xrIfDY8a,iv:4V35I/KLtTvO1oYVMK5xvX96nHrqQjh2SSgaPUXU/Pg=,tag:lnq8tHx1/2ki+/5Xil8FPA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbU9JN2l3a1hrK2NKa0d4
            YUZrQ1RvQmtrLzZFSHh5RVFRcDVuNFBqeFQ4CjMrVituODZTR0RlYXNRYVducEJU
            Qy9PRVFYV2hDOG1tZ2p0QW1xOHFpODgKLS0tIHZwQXN3MzJLUDV6dDN3akxFdzBK
            M0ZHV0tCNkQrZXdkeUs1NmFSUG5kQXcKyzYXzNsNiEQdloUlQsQlHEfAtwxAKbhF
            bEHl0eyGLCpz5Ey0Y72e/cRwaAswWf1uqLfyAtp0i5kFDQNeAudCkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T08:35:16Z"
    mac: ENC[AES256_GCM,data:P9qIlTG5RZB3O4tlHRY5vc8Mw6zAcMg+Famo0R6tgub0YPjv+oUYIEbUSZP4o5TDt06NHdkOWdcre8Pf+8WWh6uXr2JpQaVjv3OEchWA6I2TIn4+jWwUh1R1A/IPdzsaIFAprRu2HvxZr+3MCcEtvggrIIKVKxTgFcdOEgAhFZk=,iv:YiUdsY14AGMFhooPjYADuw4NYM1CP9wgKBGH/HHOdLM=,tag:SsugL/9EP7P/hJGqXjejRg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
