apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:xP2ivAjPG0YgKycuoEswNeX4BUHoFx5XY/hH2OMlwZb+JDVIT90tQyiFhDZ1qKzb83ejY0H28mYJ+1ZIs2jfEMAMzw+/JOsxvvUuJpwTGHbwzhITZ7sJPJSX7GIRH8V3XULRD5NaZ1O/SEkBXxIzBdXexkcVJaO+YnCSTv81uWoPSgtG03EBHY/SqfU2rtOaP1B6w0LfdyI+K6xGVWIw6WpzU7i97bn5GIvNd9teQB0/HY+sefVrLoAUx889/b9EpwjNfWMew+JYRr4sFmq9vSiIdmbueWrez/hq4DtNhfvhrqCHosTyng3vknqxBvFGOL0vT5AYauh/ok3kHKWOtJ/dacirWsuqHGaIQs4hqhcPEwysa8ciQW6+BKlZPAdw,iv:2NNFOPHeHTLEY2r/Kdu4cXbnAguOXA6OmdmFU7y/lB0=,tag:VgBQ5UK6K6dF3zpmXhffGQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:URZAP9ZKjLfG8/0NF6sDSon80RTeihKANrVU6+cdjNrd4fUeVcJ8sw0zkm1tYFS62Olr8WW0brCLpu0S+cvlXjw00DpkuEf2VNvCIpkuv8LzCIaYA2pf28Gg8dYYqbxxL1lWP4M8F+vfccGVK0ry/HSP4JRoKhFgeuwKZfWZdLoqcyVokZz/A1A2htCHa+mJdqcgTvdFcu+HL3phdlbpJvnRwYxBXpXYMhrEzbXY1PAvXX2GP/1DL3v1aEBTgd2apN2Vq0f0pD00CcTa4g==,iv:H3Z/uPemwkomm3n8vfvBjdsr+M1zzxZNM5uG33yY3ys=,tag:pJqUSxRxtZq4mQUZlfqIjA==,type:str]
    known_hosts: ENC[AES256_GCM,data:8QUkLWXicc3AwRbr0LGkAq3+aVMWeTZLXsWT3zdCrQdHILDWG7kOydRLOtgFPHLhmeDMsFyuYc9M79d0THibHS0/wEz/D48axFiGBp44lhQML6j+dgDOVZ9szRlNtClIdkNGpzZbooCxrEFPKjGJFmqMEHgC7HDWN2ioQ9i/nr0A+VM1hLd0Ka/aTd3J3PMJwxlx8RpdTBh6twKQZEJvZPJRFIW/yiVoi7V6,iv:ELG9Le8JPrURDTIJDsVh1S1RbpUEE/rkKUxheHRGQWw=,tag:bhqe/cjK4HS+MoVF3BLpGQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aHhPTnAyTkt5WEVWenZ5
            bk5TL0VUZ1JNYng4ZzI3TWRzT2dYRUd1d0JZCnVMVFFzZXF0WkcvdnJtV3ltKzRL
            N1hiclB1dzJ6QXNvaDRnampmK2NRTnMKLS0tIEM4VmdKV0N1eTFiMmZXcGJZWnFU
            a2ZOUlVPOEx2L2FWV1QvUUtPZ3VJWHMKc1PdB3ZtgaWtGvdhylnr+OJgDvfWGog5
            EShr9lg20TvLWZLMuGl2/CwqbTASBoSbj3XlET+63WWS80MwIkhEmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T04:46:44Z"
    mac: ENC[AES256_GCM,data:oOxjftEv5yPkUNE2F1c+9LtJHJYe0xVANJYFn54Ve1B+MwD04t8/QYV4xapTuLNMDUAl8nOgrmKNjCMJsgFo0IDkp5EMQBQPP5ZAMgzI2bFavp/Qc2thL7eRH/0Qybi7VJSwcWnqAURmFJLXynKdVwBCpEIbRHK2TU2anWk7dmQ=,iv:cXLTbp5HA9XKjbF4bfZ8AsqNuFOb/NVEubpsDVJWtqE=,tag:NFhukRykK4mFD0uOWzxEHA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
