apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:iNMwbbCYTbDP6r45qpHfbBxMeHrytQfskoQ5WFKVexWRN7MTzK6pVwZLySuyw0v0S/zWBu8GCs7DBCPUvA8ouu5H1WSpwJ+TDuC8tzUKu+cEJo+0gdgZ3RHIPIdP2BU0KeJBdIA5n3KGTf98F7a8vxFbRP1IzQnGIkgi4qvUZzHRBv1pvVruLYR1SSVRgYuwrAQ4Ao2Z3Dqd35rVhnxDcqpDJqvArFRhv1MQJcaY2yQUxWFv76DwkSgL6Jd9mk1PxKuThzugFxOAiIEVW8paO3hNckLrlNf0EEo4lraHExsNVjeGDFKiBWdMaZdO0g/h6pODDp7SAxgF638BXNVGHCPiaR478fs9DC4Rp1ArWJRleaak2r2ayXCon0Wg4uUj,iv:KwKf+lOZx4lplmlKCNi7mvhYjBJv2fSgLoK/UxTk/CA=,tag:dH5T1aNJa8MHsTtYcFiHMQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:m7dpOlJZRTJc4MEeUQB6VfmfNPfdvui0VNu5bNamFAttrrtNl1/XEtF7owUlRmMhl+tFiLobi8/VwTxy8XITOEdlWCrcG/XSZmPK51f6JvZY6brubr+YoZA7EpklvIGtQ6Kfg7/szVD7xjDkynEcMp2syStpNdCSc1FjSv7QPhlwrC+FmsaUeXEkgb0/V8/FBRawIKGJUkyy53DkgTw02RwUfzTiADmqQcvVZOHoHTijFWkU6MeTHXowAeCHIppvAmpksEAdbSAIa1Twtg==,iv:rHcQp0sw3e8CedRxXKUY7WGCjdq2cFdtg1bXFtG9YEo=,tag:xBmfYObL4n3rsnkJWEI/JA==,type:str]
    known_hosts: ENC[AES256_GCM,data:xzePP6wLTePGzcWLU2TZ+VqN34SRF4NB17vcl/tqt2OmBwLDDJXZdylyUO2Jzs89mjpKNYWshsxxOOlE5zGQ07pluXOcpfBb+G8xyjlR8Z16UlWNYhP+kPbYb4iLbqMyi0jN8OhO4rV9Sk35QC5jKJjiCOjeYsbTyo6nczSPtDgTUtp0L0PkIvi4smJRymAePqimh8/cSOEfHWPP1FTzqNQ9udRgEFEm7X8j,iv:mQRRi2MwHfbKnPV0bir9gvXWK1j52PaLHprOqne2+Ps=,tag:VT/SdaUEAj3O3p5SaaVpgQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdXRsdGFncjFmSHl2VzAv
            OGY3cndWWFFYcXN6UmNVTWZBd2RwOWVrdVNZCnpFeVpOYnNpVDV0NXZnVWFjcnlJ
            dlJQQXJtc3NIU1RpMnIzTTl3cmhLOFEKLS0tIEl4SU5uUkxtU3JaRk0yQjJWMU1k
            TWVjVGtRYlBzUzRPck9XREh1WDBPTDQKXaxRIdAZmfWskbERadLEtW678PMoV/TN
            uILgF4T3TFahDPw9YB8NCD0EUJFT+I/O1ZSMhcKSsngzKks7i2Mhkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T05:58:01Z"
    mac: ENC[AES256_GCM,data:iEXgJoyejIriTifO+goaGiPbBkqUk3uXlqsxlIRS35tOEzIyUcURy60hzzATE5QX0O0lcYXkvNtHO0x8AX8LlRYZ+eSE7lFeQW2xvA4CPKzXs3vVPHg17DPtlzM2yRaCflrR6t/B9I+Nkg1yCZEFjsOYPELSKBcoAdoQiVTva/o=,iv:rbB7OxdpBKXgSREisNMHBEzn03vo068YbmAOTTeWnss=,tag:h18K4DKPKtOO/Ww5X6R2Ww==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
