apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:SC8+r8NVaCuy5m9kJ3mGvPsNZUZ/PkmuOhywmqxv33bzpzbwZnNgSf7PnG2Yj59lIgMa9ClDyq+cw/jrLSVEvpABKZN0kYIAgj1vJH5GuOcr1UMxwnGA1ZSjcCYajM5w/6K+RrFDjEAZ3cHaUCVjcgJAsZJByOaho5CJSKVI7OUfXxder/X+iBdvXZeT20xNehQAmMDRrhXpXZw4ST/fFYIaa5t4SNi5knSXBpAy6cf6h49SKLH5sXRwe50Xf3ui+B9MPzOw2ojC6X+4EAcJOqmubj4qlvc8UKvu3G8TVz8REeqRWKHWDvDE5j8910J3PKUIUcL+9OZad/En9dSWWvefIVuI9JdAtG+G3e4z2GH1pABiumM8nMrhHYjlzmn3,iv:VCOqKv3aa4zttBTNZKEXLivtO5+x0zocUFKeyUEZuOs=,tag:QKCwN2d+sWIwhSVXvVIL4A==,type:str]
    identity.pub: ENC[AES256_GCM,data:FWkzVne37kaK7s8CYZqAabTlbDKzHzJ29Cizf+f6hTP+Tb3pm+CHdF5p8HlMFL+9/JrZjf1BT1Cmuy2y87QtUFl0cGiZwlBK8DK1mJ+92OUVhBRTuKlKU8Gcx9Fsxk6xKOKl+D9aPqfa/ogCkE4vz911NVwvo9tl9K5mbRugrY810Cm3kA1gN/o2WLDC38tfexMk8LrJqVcUmAIEXsthqc/1fM7BgbjQ/wnWUmZVQFMYlnFq7A49dXSsARJEicSSBbs7EptBG+i/3lH44g==,iv:XHg+8tTaWr+wZMBoHhAeOlvaRb5IC9Ca1RAyVT0/+hI=,tag:ouD9gtxEASqboC2NNotpBA==,type:str]
    known_hosts: ENC[AES256_GCM,data:Vza616NChGMpq5Gw00aeEdIY+vTHa3SJ85KFvhEYGSgDYW50rIviGteYZeR25Vd+tCr2LyPNPZqg7Yf8WqvVEr9ov8l+rjeo7kR+CXO4IBUesAqEgF1sOqg8fAxYiRxTBebfUyATz3PfyDUvcff23zZvFMLiWQDn7s1qzkCJ9VROj0aSXjZnv3CEIF5zMn6N/ZrES1FuG8TCJzCH7MtSh86BZUxgLz3bRa19,iv:2JAD5D7DeSzeZMODsVbRXFhDbHkJC479AiNEzU4i+1A=,tag:mtjdF3XFrWG3Y9Xm/46OmA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWWFzWjRhZy81NGhoamxx
            endtUjhCL29RaU5vNHZ3SkY2UTd2MDdPdmljCjlnTjYrRUtjU21STUpZQTQvUGV3
            b0JSemt5emRCVFI1VGU5R2NaNTV0bXcKLS0tIFMvcmE5U0RTekN1VmxUZDRqUGlq
            L3ZCb2hmRkZHNlVGak80SFNFZmJoclEKMRxIcGjhXelJdDLapQ5/aRJD2GONxQfA
            KvjsH9oBQ88KcZ/IbjLL87EUzy6ECvlPYThuj4xBa5hDv3fKnsru/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T02:26:00Z"
    mac: ENC[AES256_GCM,data:a7tzqNpqH1TwFwFUQ7zD/r2bPYCArvJIaG3kYdyXGjPnsdtQiUkV824vVsrEHIHIGUXpy797fl+Y4mgqqILwA/CJrDEzGET8GvwXxJyl1BOBgmfdODz7ouY8kLGq9Uhg050aL0MX4KVjsMby3+5ekCkIPaD6pUBOkMJDwvUgIpM=,iv:hKolixX5OA2Ogfak4jYQHTYFMNrTxhncuvsb8kefeZ4=,tag:wRrvQ2L/vpVFJus0FziUMw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
