apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:2SHpiGaZ6SCJrqB0YclCJOi4Hnnhofua+KDGFsZP0c1ZdxVpdKNaeViuTNSlqfLCvWP72BZg8bzZJ8VI5IVK23LFvE2axmRonStbeec79lQcVRGT+4eR3KulUfwFA5bOxgcL061jncBNrWsA4CJ8upbtAlqgM/y0/5TDdVfCYfmbxGY8U11E6Qjdr1ZU9Ug1ZhhRpwvxGs4qRd6SgPineoq4CvSaBObJM8uLnqJvbUU6JmrRkckuTKuSDYr6RFsmdD124nwDXbVc1bm3gWydlmp6Uo816g2eyPA2MygI6d1tWqMZt4iZqfgvPL4BqlE6otCd5ndXW9FGNWEDzbflsMzZbd66zSpZPhmugRiuLKK8GqhD7NJh+1xHv5GpalUE,iv:2GNz8cWLsixT8P4MH/n6BSQ7HOLQBsBAR5T95RLtmkY=,tag:lLutUfoUYWUCt4lcwgoIDg==,type:str]
    identity.pub: ENC[AES256_GCM,data:vYCQhNoK0mr9GH7ckb10qjl7jgquW+03+Pf1YidX6GAdKkMRj7SLf9Cvr8PK0rG0sWHbcZJy6ZczFcVocaflJMyWDivHCfg7yvW3++Mf654GBU46r+XcH/8Gq0ev+nZsN9Lin1Cd02I4y7yemzFkd9WKQwmTyZy6eTy5nhYSvqYHMRh3Xeq8tufK1XWfsaHQht+Lam1D/PbBgimeychhT41hbJ+o7BiKIE36MLuI4gugSnWbU7Um0YhNhcB3f++GYpUxc4R58fHYJxI9JQ==,iv:snGMYDtwuDnQ+23hwJVUNra80e+PYBjIqZgbh7+xh0g=,tag:8zQeNeE7VjOnPwf1DI9k9A==,type:str]
    known_hosts: ENC[AES256_GCM,data:7EAdEoCD3iVzJPm/ceRXpDJ85ytbUabser/wJ7Pp4vc6IKDrGEckeC0WaDEPdFPoWnAC8AEUZNNyrfWhVXKm2tHu5jGPqgnGwh3/NKTLc+Ai70zUAo+gsQ1sM1KDz74QUGUcQ/yJziwAstA9o67jgwLb/l7x4IB7kSCnvP4KHyyLSCEopQYOD+DCIFLg6lByoQ2yaDuBMQvT/tqfpvwO/66USUhZOQanlojp,iv:98f+9LA8rTW1QijP1ML3TSo96bj+2bVlGjHbz5I7Qc8=,tag:PbV3eyWJhJ1Nj9bXg10xew==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZXdpRExGaVVBSlFscFB0
            Y2dTcmZBTWhKNUg0eUtWNDc2c1FYck50aGt3CkcrUSs5TndTTlIvZk84cUxiNnND
            N0tTa29MOFBsKzBMUHpMTjRoSGJGVHcKLS0tIDNlSXZ0WjJrelk1OVZ0amlzbXhP
            akRENCs1aTkyTmVYUVIvb0s5NzIyWWcKaapuISnaiFMXL/XTjr/A3Zsu0ik8wt13
            Q9iheoYt9YROP/uZFZVwOjjPwg2qq8QMpIyNRlP1giC5hO513N23Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T19:02:33Z"
    mac: ENC[AES256_GCM,data:om8h/eQhW0k0ndWgv88bmsp2xiqfD8PFQFE1ElfkDASL5Tg+nSbc6sU5omgcp149+YnY3c4O4n7tYb0ApV5VHn/S4Ejp5gMgFwDGs0BksNZG6OocmCYQM6ORH3LRo3Dxq2xI6+IGwZEwDz/4C8RDhdK8MxdcA/GtbXQeH5yFZFo=,iv:650I7fam1ein9t8zcZbaR/djiDEVKrvgh61e9OH5Qws=,tag:TZ6CAIZqZpGDxre6c8LSwA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
