apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:/Ygn2IXgSxez0boEsFf0r6rr8yoUbNlZ5JMY6LX9zn1xEJYubusMlFTrPsxhLNe0D+fyK1euIV6SIYanBEGzvT1pCZYSXDRF59oRIXEOKPjNkImocHtL9+DBdE0ZKY2zExX5Zj8r24tuanTZFakkCnN2azC5py+MtvKPwcKxY33kO5IqqobSRAMQS2XG0hjfSP67Hjs6IJY7iSQry0OszaR4fXE3K6YrgsIJVzf639vlrf4sYySNChyY3kle07nv3lgKe80LuHDVNhL3dP+4574/A6pcTWiWGQWF+I3qLoh08+a1J00WBsv69ecCghOB5bB7h6qMs3KhzaIlnyZVcBvXTx6Fu9pPtE9WSO89YgaTWo8OpepxdeMVVQ89EGAG,iv:emu9Sm8i0jLezhQIYElnHLJMZzH1gOGzCsHAskuKJuo=,tag:dG91zAthhzWXKZ7WEhqsiQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:VCV5SwaIB7Y2kClZUbU4Iuw7rEcQpiZQn6elFaaR0Yc80H1OA17j8LDdOylGPtGmYXa2q1SVn+bCKGwOytoLYKOP52lMZeEBWx5tDU3TDJcDutlpHsN3f6oOkdE1dqxApCSuVxeIGGiI9yRB4OA94QaNH8DFeieFn97fR1UizFBi9eViYR5iQsdmPIqaET2rxHe7hXM+ZomCw23R3CsvDCaRSXN+F97MVFd+A73BieJD/U9lh1SBgrhMvAQrGgL5HkadRM53D6JdXeqjOw==,iv:/MFsDRYVRmt52JBwP+VhKlJgbXK4ez8uv4isN+WG9o0=,tag:l11fL0oH14huPY1qF/wNxg==,type:str]
    known_hosts: ENC[AES256_GCM,data:8+O3qGebyQk0VVH00Nh5Lq6sCQUbomPQqRoMRmu7itR6jRcTm7xq/vPdRLATR3QNkSfK9qIqNPiI1MPNFOBzvCligO6zcuMYg0W+MWd0xtzmPLw0sKWJCbNdJdsRK5nqnO7TrvG5v60pTsLqjjuTc9Xmla5GtK7AesOjUYyZwGzuWg0KW5xNqzG2MMFrCYHDPfXiVpGevhwklcHc3xNI71UXUDblpYMgpx54,iv:og27Mzfd8bpGkZ19F746CA9Sf2bXVt0rrpzgUqu5w/s=,tag:MAO6vdzBxZUv+0V9wpgN7Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyK3RtOHdYUzdhQXMwd0hn
            cjR1MzVyUitKN1NMbGZxWGpabU85YXBYdkVFClpWNit1VzBDOU9sbytaU0V5VENy
            VWNxNmljeDAvRzVPNkZYZFByaDV0bWcKLS0tIGpEOWwzZFJ1czN6QkFmdHRtUkww
            MVJzaDlOZGs4T0lTYkdCNVdEdUNZWDgKNxXbBNREnoVEaz4P7ldtwT18sQgcJDNd
            Dr2hAS0IOu8tB6cC39WM/v598JZZ/gAS5dG6pm2jQn++I7Nx1/ONdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T21:10:54Z"
    mac: ENC[AES256_GCM,data:/A9s44ApWnLg2ERS5leEMXAr1aVWC2/It9JTRPiMewTisRarwhpFF3xf7XLxKYXMhJ5Gr7wVCbsLt8STIDpWVk7zhXWvLDt6KJBtFgnUx+LyVwFKOz46ZzBu1f7H0Ry/yGY4K0UXQEBcwq2bvvC1CtTmEfTFZpyX3Ce4MwuIjuQ=,iv:KEMvwaa/zUO67OYQ6C5AupwQ29BJTiT33kHfeaCZ9D0=,tag:OUL9zuustynTsRiebBQ/hw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
