apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:CXYU0SA8LUaHCczwPJ9lzG81uc+HCmN8hmSNPhsN2VSkFa0Xy5u6D/UV49Qfj34tGZ2hq+UKOVUf04r1aPYRcmqH2gUdBdcvg9RuwP6ZGTRIBsLsJBEkUPg1kSSAS0xHQuuAuOaE5r30dDY9yCvs6gQDMhq4L59LWPsXsCJv857HtbJg5F3A3WcTDBSwLsri726W74DLfW9PUu+XtUBzgjaDrD+B1FaPfaWr/M3ScTLzTViQvTAN+0xTpAgcEINXV4dxqlIv2d14MJTCTeE2HLleVwH9hp+Gw3qbRsH+BlOcdWqfcXT+IT2RfSyNmmJ3goZcw8vGsDQBkcqf9vgqjlpbI2Z9YSXRXuU2gbeHfxrBr7zQOFGUVz7Z9tIVwXwn,iv:FK+HjbQaRo00US0HJxVtGpOoXaXosvXNymW1p0X7m1M=,tag:vrynzx5zbLvYOYA5QOP+Ng==,type:str]
    identity.pub: ENC[AES256_GCM,data:Z/k7iczP7WX8aNEI2VFKuI3XSpEoefEXvxZtJJNEWJD74yIJ+P7GrqMQhn9telLp+OvrdaiaAmEvVEU1qBIPlFQdjhvv33w+rESk9vnYswDIDyBoEJd/sQgi8F2cVoPdO4AIXZmR0iemlvEBu8JB3VMeUCNcpbrYl6gIZ/q7ZxhTTzdzaIL1e1tzHDFXQ4M1nVjc/hgTIayHlK4FZ9aaATd/Q3znRq3k6YdmRLTEFE2EDZTcog+wRW0X1HMLuAEkeCOUvHxhj4SOpwZSRg==,iv:S16jq2Z4xk1q4ldrmR0sLT9bv2OtoE5n13jwieMA8y8=,tag:Ih3uyP7+QjPrxg9MerY94A==,type:str]
    known_hosts: ENC[AES256_GCM,data:W+p3dQdEJtGlTZsPyBpgaaKmlelfICMZB+RucPiS2ZJDeT4SmsSIBSIPBKkBiDuPEFYBxPeP4tNq8TdTT1o1QzTadiizaE6CYxbAsuQWT+UvECCjmgqprqd/c/wrk7585oC/g7q7PqcJ4XkH5xKgAIJHMKMqRAippmZV4i81WMKyNST4J7b3KFwOrCn3xpgUQNgM3AOgQju8XqLaFc1fN+iI4Swtw96Xx5ft,iv:tx9Am2DDTSU89/fikrNUt46VoCdCGExjCfmvxC3PtoY=,tag:rC/gk4OIuZ0vUz/DAmyM8A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcU5MUkRkbFM4dERnamdQ
            SnlSd3k0VjJ3NklRcVZPZExySVc3ZURhbXo0CnhKeDdjdEV1MVpnSUpEN29PUDhR
            TVlNa0pmT2YwaFZ5SjRPdWZPMCtneVUKLS0tIHN2SDE0cEE2RndzdnZHSldJL21O
            WDFvaGdLcVk1MC9CRlc4Rk5JbTE2cjgK228CJiI5Zesffhwr4+a1gicbbJeos+YQ
            33oc6Ruz9DKlKawB2IiTU+yiPCBj5MuENXqGYucgsoaFQGAtUZbSkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T23:41:58Z"
    mac: ENC[AES256_GCM,data:QKLSg9s/rU0c+CRoWlSiiK75++r1rZb6twXEGzqsfTtk0qr2+s1+Fc2mzz9TzPbgWmrXU1/DWBg92lzgn/vcJvByx9zSIXm4hVtu0P4ZLl4QjIrN0uB/PBm6mpSfmaCEIhlxvuQFtQyDvefpyYcJ1V7jM1qHOPxZXEi3C9AsSzM=,iv:CRng5MuXgeZxb/BejOUXYcVzH+iyplCDT2YqIMEuIvk=,tag:qLSFXtTuim9me6Y09ciduw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
