apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ZRMat6tByrCVOn9O65Q5cbl3JWIyIvbBIjFzw6J10CD3fch7hopciQvek16uAt39KTA2udAx9gh90b2iI25XPo5GdYRmvYiR4DgxZfK7Bb8yU+69UDAewJ44sUEvmIjQRWXin2rXTyjP2YL4fV6HVy6vy55XUFqENmkwFBo/Zw2hUiX85zrlIwf+NHv5iUtuimjAt3+zkb4O1qU7MpB8mOW1qux8nQFg05d7tuP02UXGTdiPXKXRhhXVFo93fvQJsmEDYYr6RwKkTFAZVeQQyhuOKcnaxan1q0QBoMCZyBJP3e5+w/0gp4II+RLlThEb72atiXO7frd9MycoNAAYZE8bp+1jwvnFpStfOb1dvYRvIMvOt4vojBZlUqSQiOSj,iv:hUDspbe/PEtgJMLRueJsyN7+HQeksXNBeqW20pNoipY=,tag:/X62u4izBf5K49bmlkP/CQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:YcJ2l20SpFvAaZ2H1IH+5UPP5wodpv1qQL27pSEbAm4lnVsRUgrdT2LXyPg+qKCRO+KmiKJjqj+OpR9qsQSAAzQ5/wyPVWdQjQaAlF2g7MVzFzj4bEGBZQp7Q9cR9PsQQcMdMcTYMtrmkt0pZjXLPD9l+f7M1KPhdkiECQD2sIM2i7QUvFnlJQOiHyVm2OTtrKXX4vmH9ga4C5WuCWCUG3NNKn6N85LRL8quVEdk1FfU4KHhqX6H1Gm4Rgo99hcgvGuj+lrMd25LBAzXXQ==,iv:bu2lhPpwBP09gbVKkGvNEmP3qObfRM70fY00upwHC9s=,tag:YdXuJABF3RuK6lzbZ2kNLQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:guU+BfZARzEEWCDsrKGj6Z6HzowiWEXdyWv9F/htT0x9/q16wiSRjg2wCBQibdDXzBg9ib/eToTfaVfClpp01j2ANeS36ZxaHiBp85qcp4mow1Uc8qBj4S5tcEUCHhXU3joixM3Twoc+rySGLdpHYfLLPzdLzmG1AstIXT4txn/xVTkDdDgS3JIIzizZ+7EuJSiMqpLU+KjUHhGdLGsl+qKYXAbW3QIHdO8b,iv:DiedMLNfDvWhJw36aUNp0bkuCjKkx7Dn0Tv+JAkW2JU=,tag:Z8fF37uLSTAJUd+ZQ1X1oQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaK3F2YlNZQWNZVVBJRTVQ
            Qnk5c0NPQmRJbUR2V2xRejVKZ0tFTWRUdzBjClVBYW8rdWhUSXNzMzFyRDFpeUlK
            NHZLbStOakI3ZituUDE1a21mWElPTm8KLS0tIGxLU2VXS3FlSGJ2TUh5ZXZ1czND
            Q2cyL2d6MDFFWlZsVDZ3Vkt6NWFVSUEKPl4ho9OdBWM/nH5KgYq5xZJfSSwMGN7s
            dWWWV2lRr5sh96IT2wAAJT6J3xOlD71Kbj1zV+cWgQUXj1tis5A6ZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T18:27:47Z"
    mac: ENC[AES256_GCM,data:BV9bEzgE71ezzPwng7QYcC0nlwkK5C24gfHSjWBRgG37+lcA5+MkV5tEIuXiSVmD4jWoghXk+zanHcsEIW5UC5iemO/Eg/e7GDZDD9Co0avJ1HBVhRMPvRV8z0RSG9AAF3JOfQE0AsXKr0/4CA3jYermOZBwU5L+GvpRuGUINPo=,iv:Vh9koqlRA5e5SjWfIktzPxyB75J84ErGWg8Mib7Mkr8=,tag:wEUyB7RzEvpuUh98u3XVdg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
