apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Rb4TCO4YlyOtAirNkV6Bns1cfXTqzxrhhpuF1W0Q8JGjT0QvxRG5e2COWL/m7UW9nUBOHrSvppYd3ZR3qx5NFGDtfxzkzDIgI79UzJLjzXMhDz7THaEzpZ8cx4etxLG6N4wVRzKB18m3ZzpSie4KQw1qOvRy0aMdla6WQOGriiERCK9gM08WpDwVwAwhpC8fWu8wZlspgm2HwTsFka6233B90mRjgKb+6FlCiGF62KnPWcBKFVcYWEHelmT/IbEK5+E2qh5RFG6NlKDk5kY8jwvovIjJ/1RZ3F5r/reFjF40Zi+JjVLCnENOHNuu8RFLdZWJxYHhwIS58VpwLsZbELiUMcNqj4fESDaMBsQatM73aKTNmg2UI6liRmmK9SgG,iv:HzdH4ptqlg4FSkGWEqDgxaJs/sZCOXEsFl2j1CnM6hw=,tag:XNa0S52kFAu9vPhKhEpE1g==,type:str]
    identity.pub: ENC[AES256_GCM,data:wGKrN2A5C8PZV0WqNO0c/O85AbDZL6SFJdbAisxm4WtX48XEf+IEHVstzeQWLKRk+eo3gYl7vsCmT+X6gVNAp8dDUhp1odyWqfmxbBVRw2InC8qafvZDQpjLP6i7woeajCYOckloke/kWXlRmbeXhhWl7+mlIHRSx0Ji6URSbiF/MYH8yMwXfLQuD0LpJr/3OfpbJzm8MsgFz05zIaYx+M84zT7c2Yz2hSD4bIclItQS+4+u4uB7xXr889YHZwkIPA1jaCBa3wt6N5IFOw==,iv:vC8cty2L4vsIboUX8x5xJ7BQ9MEKBpy9T3qaTqIcc+U=,tag:dAROQSB7yfo1GhWMEqoe1A==,type:str]
    known_hosts: ENC[AES256_GCM,data:KB61Ia1KBmPfRvtZPf3qRpieJ76ukKX8EMpfXjz+saSeOkIbvPNObknxJHvZCk8K9KJRpJ/GZt8bkpDw6/YFG8h7xV310e1NcGPAxvuWdkV9ih3uFnzkR9ftjqqIs7ueUaDbIH12STTXzTnHUZ7jySqKVap1uhv2oWeZAWu9Ff3t7kVzAOAIoWdfgF2hhE/yiX/9ViNHshHcTQBXbMHOGGCQA6JwXOPYccMA,iv:Kg4gqLoVxFOSvEQxfwiXAktdJKvj9SSoA4m+/0cGyAc=,tag:MgmDKzzvLt9SW7OVLI5x3w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUjVJcmlkQUgxUUZ1aENH
            QnBxUXBiSXgxOXEyUXBUeUpxQ0RNSWtYVFVFCjZTUmJKRGk4d0x6ejJVUmxHb1Fs
            OTdFbTdJTUdPQk1kZnFLSHEvc1d4TlUKLS0tIDRkSnd0Szk0S0VtVVJYZVZpTWtF
            eXdGbVpWNFA1Z0dqQ1dZNzNGK3pxdU0KMdMnnQz33B14lBVF4jzp+vFm0hEQ+j+l
            Wu2py+xrjY1JmrAkI2KYonBx6abazSWN6bvYVHCBXPalIL5+Q4F+DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T22:26:56Z"
    mac: ENC[AES256_GCM,data:8i8tN96X5Hn3LpOcw9V4gh1rePHP3Fo/mCZCdTW4Q0t6tjnFa8FgScK8egFOucuucPht4A+/zZwHSJWwt2lqbI9ZJ0+4y1/rF0IXBCbCBSrPVlf7iOSXEZa86TqT+186deIU1QmQOEWNb1zALQmDSEJlnH+PQVRwqCBwDdDqd2k=,iv:8tZZV7qKEx5kIzFPF6QanqTjGl7lmnGG1Nt0I0wsKg8=,tag:BynIgQszGYFGC+IRZ8+jpw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
