apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:58cy5hIyBCOnkD4kSOLPtorTCL9T7uilK3vyHwKvI0D69u5x6Eqci92QIii+PKT8d3SULUppZ2WwDdPucn5Bh6ZTV80FlSmx5uvKMBggyHSkXpg6yZTP/QsoDoRqyzKFzVCJbpRAO33obJvguFbMY0WXs43Bkr7Vq5v8KIz/KO3hbkaTg3tgxyomVLlZtZlb2xYTcqdNTXEYXlzkd0httDG58mNxLnlFSe45sWxDR/zxvUsD4rlQ93vQ8BlRfFEqzj2TBQk6yyTNEmAxIulEWC1kRjR7gCyBgEZnrnVBE78dvhS8Ii5BsYicYttQkoknN5CJ3kWPyn7tPKUNCX8QYCo29nBJwyQZpz8H4QAw+r2dDYwqVl8bhBXyKkl1VWLY,iv:LNdkMj/iXoc83FDnmiR2FbqbDx5Lh0rN1mRNmKAagu0=,tag:jOe3UoGwt3cw8VPGtw8LtA==,type:str]
    identity.pub: ENC[AES256_GCM,data:Fqn0WRTgmxyPUeIRvB25x6tRwUdXk3WbwMyZK7euIIABHpyHCvdqDm8iv0RCd/KlzVfAhOubqxcdR6RKW/RgExEwTWqcSxfAj1dBeh2i68kLweFIvFObpjHr4vSrEW7yaA00QyN/piBJtUOnn+TuPIeL5ZdqVJTOzIXISY1D3p9fVZnPhXX9B/87qImZMYs+kOr5etwvS2Q6G9pLRDFRZluxoMxfqHdJZIToZzyuXZhYpqGG0p5C1bT+aXZcpnyQRi3Yju1LC2qYHbj3+A==,iv:MPVUc0oQpTyddIN1NxWlOV4ZszG79vbRhweaxMpXIt0=,tag:wm6M148QOJtzI4YxZN5d+w==,type:str]
    known_hosts: ENC[AES256_GCM,data:olzE9diwVRGyzrfj4gY2PLpT/8PsSns7+94tcGi6nkrVy/gQh4ijGwvaAQF4WVWhuwZTlRFwOTn6kOapkKmPbHZsZFqx9ekI5ACUevx3seZErXIkMscn/V53e0mj6vtD72pGbNeOTsGXZzq8msweYoSeC+vhnkA3v2f18D6jh3oTJzwhca6Cg8WgjMZhgNNidzPLcrOKGzf256U9Bt57CkMJhhC4g3rGaaWy,iv:c31RSNyCwJBwcI/VS2FuAhoc8aZig013LDBqagdVDzk=,tag:r1ME01nU9v5tt/ufto/Atg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRW9NeVNRTGNUNHN6YUsr
            b1JWQ0Q0a0tVREFNR0F1Nm5rMXZtQnp4Y2hzCm8xZ1UzSFc0S05ZOXBod3ZMVC9F
            eUxaSVFZRDl3b3NxVGpLYnpRekF3TkEKLS0tIHB0cW5VbXYyYW92OW5FTTlTM3B3
            Y0FXejViZ0x3Yi9BVzZ2VzZtR2Rob3MKgenj0MZnm89f8if/jCYZXnDEJXZIUQdo
            mig8yRT/tSjPQVmBU2lpsZuHnXw/Rs0r6qOBKlfQYEvXC0zKAJwHMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T20:36:09Z"
    mac: ENC[AES256_GCM,data:w+L4ZYmOKiJPlWVEyxGji0fzoZZgXKrBjksCjp0E1CWPS+kM9vdrJAtpSO9aCMqqywUFNEsuKWP7ZeC+3Pug8AuKpw9h8IgDc/0d5gzwkCkhz06Kiqe6P04hSIVek8w79hSySAl8xeQ0o/X+ZpVrkhjIOAXm8mV5gUN5vJKuK8k=,iv:hrwLXGRRbOqobiYWQ+L16+YppXASAWMaKzwFPSpQSDc=,tag:eCVCnK4hxzcDNyHyWjI6PQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
