apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dwffxU+RPmaO81QbDQm/x/VmkgiK1q1aw64sNib1ruzfm1QTt3iSNSfxx1XpTB82TA3PnDPfYs3njF+aPZcP42PT4/cd+Y5UXfJzrYF+WwRld0tJBvgAI0qHKjD7fhA5rm7n2SPSlLNQH0ZkXCSySoNPzlGwDtEzxkyVY+WrO+47VYGhZuJtjTBZ+parc6zZ+2v19BmQmcxw0FhF850aHerASxWt82YJsPqfFMfSnAt1efY9Dh/QPlRTLkP4zC6aQZvNUaQ8ChGWV5vk+V194X2UkkVIrokRVyktYDH1XfOKlR1aJjPUyEAhv7q2lscq0z/VeBGV5gccMTrg0/FKNRtSTJc74yPjHWgvjhAnNUn8hGsXC2tgqm7zK1IdcbJ7,iv:GVEQ5po4gv7YGDp9vk5LlNY/eMfLUAeMLvs0XWozKMc=,tag:gg2SfWpxUV4KdHFvhXEHGw==,type:str]
    identity.pub: ENC[AES256_GCM,data:wNp6vxdT9mj4ZA60OLhw3s9Hdz3FPdiniMd08uvsKvu4YhsY/Z0Nr2GRxQBfnrP7+JjMwUVNPJ6LDp1A764YRDcd3STAncQ3KL7O8Zp3q2WD13qdh98gnXh210rtJ0bq/D5SidRuboHIieG87v0Ge07EHnEbYmtlhH3qJjOOgdfUxg73NsJ/DmovLafnPwGbRm1BGn/mJxChqKZgvJtHGe8TxwkzM5VaWySiIiO7U30j6O/KP1N7BsC7I7R9nm5ENy6d4jaM2O3OUfr3Vw==,iv:wcD3ae5TrC84KHuZUqLy8EuHoNgqXD8j6epkEZf+Shk=,tag:KCbwKCD1xuD5GgVdsrbRXw==,type:str]
    known_hosts: ENC[AES256_GCM,data:i7TGmQQEQ/bu2/n0+b6fWC0+nZ/2LtEdLZZPfjuAvMxPdBobggiSF5g0jqdjfGqMrq67QXIVx9bOruBNzwcHTqR9K6beL1KM2p6j2LN21gSKWKFFXOs7ZtgFCwIoks8bbQRxvyLupv4b87ONl0ePqfY6cW4GO0kdPnI5HUv/y8xbsW4xSNQ6C4CX5pF+ARlG9NAqRQiFtkJQYChteUtQcFL7J9HNtpqxau+O,iv:K+jW/c8v1F//QnP6hTNq0mBzc0kkFx3VcuTrTZ3s+8E=,tag:f6MNC8UJq7HGMumWOnT9qg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFenVCSEJKd2wzcjhBSVow
            VjlHUzJCc1JoUFdYNHEvK3k4UFM5VEZPeHdrCnNGNXYxZlJxQTRDbElvSENzUnd4
            UThwRExhV2trM3NlMi9GNklBcm5sRXcKLS0tIERpMzl4blhFcHRpMHBlaEphVHdJ
            RXIxRG5OZURPZnJPWDRweG8wWVJwMXMKCrPn5+i2S1uxYKT/AnpF7pYEWakY+gqk
            FqCEcg5uvJImmc2LAq+i8lhYGS83PnbFi/W+kMNrkCFHjSu4qlQBiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T02:44:54Z"
    mac: ENC[AES256_GCM,data:zNi9Jye2JRjPtyEnZa2Ea5Mk/lwX6KFMw7pLVVaKmJPDr+6YhpttAuotkrlzm4f/lt451AsOHEzZ713UNn7Sdf1XCCTGOOHi4qbGamMhIOOuKSvvoFx6u4bEZ42gDok73JXl4xp5B0tKtPCWVVka2DU8X65OoWKod+82D58ozr8=,iv:BVZU8Pc9oAI615nbkChVFJaQu4550Ax3NngsMgHfSUk=,tag:GEBCbklZ+I6rrdyr+pmy2A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
