apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:/OtA/Myeu6h1RYZfCjohoJ4/QyMb+3cZNVd6OLJM5T4gKNgO+7NEDxOFO/KFTRHMmWJbEzLRKrevXEu30CgbpFff2XDLbEaau/l00R/Zm/oKI5EVQ0Bk2kpc+MQ+OzWWCyqtg9aEJtGl/J0sB/v3Rgn0zSt2WtnQCUVpaqVBQujkeD3UGponZ1Z2pzhOEV46Ywo7Q6A+rRsNXAGF1h9B6oDYTqFFd8YK5AYf5tQ8Ql38u0MoXevO9V6WaKWGGdO8gvaUls8ODt9y+vYX8ulPXzYb5HtNQmCPEhMR+as5twHxoYdtGlgaICwUWqycqYiL1OCMTqnbXI7cZfQezNeLCPI8/HciBWc6s7WPiqFzADaXKd4L0L1r2XlIlMAFpGP5,iv:Wfb1RJBlJd3inVIuxpQW/2HkRM/b8yySEEn8zkUHwEw=,tag:feB5fjptrKEieoX+8U4vaw==,type:str]
    identity.pub: ENC[AES256_GCM,data:qiumqBmknN3CboCALotmFebs4EtFilYvCKii4UrgGV3xqoPdFHBlmRnwfe5C4Pnnj89aDFSS1DMB/DZSEQ4rqkeK4C+WFMdfpVd66jztkLgiIe0YBd30rWs/vrCMpZKOxgIm1a6bEE4FdLZGr11wi0+JvMjP9N30PH3JedWM/shQaQc4aJei/8y2WFslIOvbQBk6fwZpwM5Bc4ysB0p0Jh00hQccvbB1INvyfLJMDuJLWw03iedA0RJ8PPP43PIGkD4Az6CS/7UySNospA==,iv:/ywfvWgvClo4ReAbmLV28YnIsGG/Y6hOFgJGoCVcnWA=,tag:RoP0egqR8fXihjpfmQWvnw==,type:str]
    known_hosts: ENC[AES256_GCM,data:vLIhUy/4loaSk9wqxYqLdBtV5BFXI1I7Oc/bU3k6JcukVSK72egN2j7+4PNAaGh+xX2JdgiD9iw4CKFlgaDMZm1bKIJuetgZk0LMFXoIwcoV4U/Rlo71THfIPXmLWJgE5WOHveXqpT9/N9rdQFB2By1IDUKNQCo/0SABxMoUARsstvNm2BpnIhf2YWkT4ThTHKF5yndLpS9yDS+iXrVAVPcfpUtGBKlRLojY,iv:vqFyiJaLCyZWVIgQE1G02wp09Mssv9Tlp9n8Xm46qF8=,tag:5UI3XNG9hY2Q81pnC36ClA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaGphMFU1ZnlXelFWWXpN
            OWJ4UGFtemUzTXBxNExZTmVIRHlkNUZERlNJCmZidk9UUm13NjhqWi9tY1cxL3RR
            aGdVMTVoSkNraFhnZHhBdTdnajREWnMKLS0tIENEUndGTCs5akhaWDRWRU5KMGZM
            dXBrYXpyYUt6MjFLQkJiMktzQ05rS28KTRr0RRIMUBXjAbmMJHKckpU9SRn1M/Tc
            4ayIDoLsza7VHcGp6ggMOeAO499Q0mGJYweb28/1AkgFRZXxQMUI+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T18:12:13Z"
    mac: ENC[AES256_GCM,data:+MF5zL/1q6TWK80uovMn/9F3up/THi0xSZBSoCg0i38ltvX0cTXBqnAoHyk3iRQuo0r2el2WaM2jzd+rOvAgZqAaM8ugYWOa8UmY07VSr41pEp2Ze1aigCSs5XRt9Lo2OKA5gsIv4guEFwxqD0sckD+6wfyL/wnt7TnpEEemx/M=,iv:qkoZBue7mMxgiDaZdndVRNckW6BNmkaWjK/9BEtsbbU=,tag:8pUE7bHCvsIGV/AEUEV5UA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
