apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:99yoIdDee4y6ekUqmJYsqWWgzrA9hksTqVPH3K8BAdw3JKHuxkbwwDAQxDPAU2W4JE3hFpLXFL7e9OGviTELoKyjn2SeSLZGTI68zkXUe5iKcJiYJuamR+hD+IzsVMIFKcGS7IBlEcPzYJjmC3Xe843XAKYkDYPhxASqq+JOEQs3Ga4Ib1/Doe89wQu9aopNnP+lOBupZC9YbisdrFB9IrpD7BBqAT8+dayqNOfE+3l3amIH831QQj3r6WvJR6dqpUEdy7RQf7tqOKLwms53e/s/r9LetD0AlHum9Rgs93Wk4TgDtVC/XZdqFoNltj/aZnSJpqhDqSceZ+wAEbQDBrvYmBg4nW8mdX2QgyuroXkFyrIP2j0/BIAgvDYWf6Q4,iv:GxRie41H0VU8fRoQoQANlgIxiQtRGdpOnNkJl4yQWCc=,tag:ZnKVAoXIvcB8o+BSPR7oew==,type:str]
    identity.pub: ENC[AES256_GCM,data:eSri7quHKlDmzqy/jSNG5UIF1BugOFmU036bw2S/HLV209Dq1i0feBBwt5bldgCw5Z2t303fNsWLa63Bpi7n/RC9GuZkz15YeQPLM7HpFmXcHsfMMugFrEBu+4ZErpCBCO5CrF3L44JRJUENAmkxm1ciis5TP12nSPJMz80MuCYOL/jY+edNzoVRyBJhutTLhbFiqf6Ex1VrKNv4YKmKJbmQsCTU/8xkvqsTwWA8jdvmoVF5P7PX24pR0ho9blIcgqWXtqtRoZwj2lSgNw==,iv:DxRVj+v1QzwzeooeLNO0dKhcDomZwVMCVuSUvTqB4QU=,tag:4ktZjZ1UXczlT/w/RW7Mcg==,type:str]
    known_hosts: ENC[AES256_GCM,data:QqKAsvVxW+mpoTYiAgBzbZIsrpn1EmxcUX2C4sJcLEos59FrJ2GTSre8x3AzxeZXBtawJHkOqkzVJ4VS0ussQr+BvEpOv5fAJ5DkQF60Mxu3IFQGNLnSnI8el/C7VlnPEI+HfLXLpV3rzl5Urv+q/0CMnnCX03Y6PD/Zd6k4dQIe0j3OIn1n7VqcsoyNRWpzZEPwHvQdIQRwD4l+UKfbGsEs8EFJ0w2sZN1Q,iv:xVhomSYD3B2AYxtasxr8nH+tMEodZgCglYiAbTExFDs=,tag:xT/bDJQ3oS/cAXxEMDyukw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Sm9zTElzdnZGMkVUNWNH
            RkIwRlhBZEdzME9tM3lVdWZwS1FCL3VReDBFCmF6c1lWZ0ZESWNyc0RGZnRUTENk
            TE9yRUtzSlRTSE1MWlhoZlNDd1piZHMKLS0tIC8xRzM1dC9BcmJSK2dGUW04K3hN
            MFRvT3gyZnE4NGIzdzYvTzJyWXB3R28KHcwYFlkR6INt5Be9OfTN6wtv0jNIC+ny
            fPHcBk/K/0YJdinxHT6HZT9IF7mw1/ahAneGvkWsvvZfdLfADqFrxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T08:31:25Z"
    mac: ENC[AES256_GCM,data:fAohAcprdviYUlDeaejH5ghEV6Kf3Cvr4+u8KNaPht5mYCh5U4daiEQ9vYnksKqnktGZyYZykedEKBxluvpXquNW7rNhhcgaXdreuQ9iq9cZS8QZ6gtl3nKv2ZKkgj2Dvg9/vlbuZYLargTdeLHPvmQUwevgYnDRx/YIkwlo7oU=,iv:VUOaTBr24+oqEu25+oCyBet2BISFsmAlOTOLtDt9hng=,tag:rtzAvtq4eYq+1pmKYrhLDQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
