apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:SgL6jKGNkWYu4gOBU+ksZVgXBIqQdmWswAvALwj9WO8r4P4MZi3Iz/KT97HKOE+xRgSHgJ+zM5JQFciptw1csKCv7sk+jr2LYWXjtsEuxGp0Eb7N6KjGsfFbIUCt2hKX9ErSfXO+KIoDDbnKEGd/TkUKBa9rZzj80lkMPfiYr74s43KxzfrFqk3+rdopxSnHB3bbfO88csEstDuI59S3CkhWi+1di4ifUuh5PoFkkC9dbRQaH3dHFh/hu2XJbAPPsJuVeAJvh9weOUtJsBQyEWzerVdU+n6z/epGqtuZJlmcLDLImgfS2G+onAfuBA/0Eol6y45Rz4Laz3x0fOnewtW835WQpY6iN1Y1xFOfyoUTcEnrva8NxQtUyugXibEP,iv:XnA6AasFTsUC0Wsb8Y2T1TOBfW3BSruDGft0TELOj4E=,tag:E8liCfl7tmp027zCKFqwxg==,type:str]
    identity.pub: ENC[AES256_GCM,data:YGq/N682qyNK7E+KUhZHWIkFWlp19M4g3vB/Ft+6rGPFG6ScnAGPTHMGpq/Wfanu+YLQDA3IFv6TeYVHG+JMsy05eoXI4s7Z8NKtHQ9r6mqf9ntVi4FZPW9UJ5KUZ9r/5gxewCEnhbyJ3luSnsH2boD99EdP9m8XTptJtP+nmG4D9yCNw9XgCO6KIIwioTfplt0gWV4UZYDLSwkZtuL6nQnyw6WW3k0HgmjSQ8svc9leTx/QOhVmTgvdrwML3BTh5CS4HMLwM73wKRgn0A==,iv:3fdDbIBsCkoY6EsJORgPvRrVg7ZeqMXtdKsMOt9mzDg=,tag:2DE6zvY31Qm3pDNTUrQa4Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:4L6l2G8IGtHnGwIDy5f9vB+w1Li61i1zHT3POcILqOsRYjVj3R+Ry6FaciZHBoBHl2omeHOiCqofa0tQt0eiZuRiRGnDgs+y/dU/ojHAkvzOHPwwoFVsVl5SkzwjQed5DDS9/Aw/MJF9iw4FGYI+URWfklkyRhvdbzWl3RYjs0dpqi9Ux3g4/Kta7dniZNQQBPQcf+EYj4dwNHrDTRPGmwI/E5bUrysWJNep,iv:cmGff6gJoFubFnMelVSpSNngEzA9xTgyqQjHlb268xU=,tag:Ozp390evA5oxDRfC8htk1g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSzROYXIrN2V5TlNzelNE
            c2dCZmw3TnV4eFFCUVZsOXZOcXo3bVJHOGlBCjViMlE5d0N6c0RaQ1BDaFhrM3l5
            QVpaVTNKR1diVDM3bVBTclo1cW0vWHcKLS0tIFM2OGROZ1E0ZkplUVMvekJmdjdm
            RVNNcWpJMVpmL08wT2tkaHd6QnlJazAKIuBXqU0wPjR21xNA0i2EhKe/vRBGrxoH
            Erh8huTZSWE1BC4lO0uHcj7oeyO3t4OGJGURFm9efR+EtD0ixfEpmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T18:31:47Z"
    mac: ENC[AES256_GCM,data:MqFxSU/8cjz2ukFjT9EbYaT6DvZss9A/wcVveIZkNhw59lTwo8OmSB78yO9xS5WNFogAyaBgZtHSu58UHOutII6PPLTniO8nzoItlnQLtyg1pLyAPjhWOF60ljkWuoY+dbZcp6nO4eTIQVvvz070RckS8Y75sA+boQq0Kt7EMuE=,iv:7NE2Zb3Jgivtd5srMZh9JWGsipgL2ASY4z2Sm3BMkV8=,tag:bnrB+/n4cCkZ+IwqqVA/jw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
