apiVersion: v1
kind: Secret
metadata:
    name: ghcr-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:RFKSlA4X//Y=,iv:lNWoOGUjoYEGP3sJDhKwT6xU9rBdjPKMb9QpjBlRPAE=,tag:/+o0W3Mcsky8yt807YzExg==,type:str]
    password: ENC[AES256_GCM,data:uw9PvQzjBIKe+WrWKGoV,iv:QutSBPFshtdjWw3dZM7ThpSpGzRjOjlb0o+93zyfgBA=,tag:D5RhCkbONVLHnirZm/JKsQ==,type:str]
sops:
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVFNOUFNoQnl5NTJOOU5q
            WXlpZVpMd1V5TEx2M3RKbzh3dkZMY2ZDZ3dzCllnN1dNcGswR0dWVm9iLzQvSkRN
            bUw5elZZaFRZOFJwMjFkMjNOQnY5N2sKLS0tIE9zTHVLa0hBcXVjU1I1K0QvR0dW
            NTZsaTF0S3pvdWJYVVlJV2dVdlQyOHMK1CedboMrc3Y5/lWxDf+5jF0Foa20DSgu
            LxRTk6yL/9wUGBOIZcXDYjYBYfc01J/72wRjAjnnKKNMEwjJkOBUSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T22:07:48Z"
    mac: ENC[AES256_GCM,data:S7ipWd2xyjDDVfpwRhybXUAQWdLotflA18CXdoDReN/6GXejvqmxsbz3tQarR3RIVY+yYv7l5MZ28PRMNt/y+DKsmctkKEXk15N26mHwsuCgd3H0TOfEMXXkePxsAhopc2D7qzqLPHXc6Buj8jVMz73KDKrk01K8i4WDOPMkLEg=,iv:P0yGyxGIQnKMhs+t1bsCcKq0WETi8gF5zY9ODXvxRdA=,tag:cTEGdmM0ARFwUVygN2iEdA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
