apiVersion: v1
kind: Secret
metadata:
    name: ghcr-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Tg6Jworc76E=,iv:js7BikpxLqvlH6X8byIcworuSKoyRTLrnaK1FcCUNbY=,tag:I08awHmw2Z407JQrGC4UiA==,type:str]
    password: ENC[AES256_GCM,data:JmdDjO3Fjnv/V1OfwxvR,iv:FH77lGEpXo+nWmE5lTvUUUYSEeKaKGNO67RrUzPVmY0=,tag:rt9gPkUVCujYn/miQBHcbg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ajN0UzJPUHhuYXhQVVV5
            dzBqaE9BRTRLeGR3T1NIbzF2bnBHZkczYW5NCjY5dC9lZTA0OXFnKysyYVh6ME1m
            enJOQWRDV1RKYlJFZFhlWUNZdVAzOW8KLS0tIFl0S0FzS1pKWlA2WXlNYmpjRGFt
            czBxRHpyZFRFVUw1eHo0TFlTNDNxOUUKj7K3fi0Pwci2lLGfCcSdSV5V4oPQn0k1
            eOf5x2/BsHzHPylTDMpNQOmD29cMaEYm0cEGTjU/PRQfJdVijAggmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T02:35:57Z"
    mac: ENC[AES256_GCM,data:6hxbGrcsLGKrqWBx1YTHwYL1g2N5xaiImAsnpA/H/wqzr6wGQtknaJavlP7YS1pL3ngyg4MS9Kk/J/OxiU6Xk+79SjG1sBGAC4+fnve3B7Ju9zDUj8Q4O69A5PoTUgN45GU6+GxLeey+Ni2p3JitfADPc4HwyZJGBmWhDIOZvj0=,iv:VOff6WoZT2QGMCub2QEcQF8ZCxxxRaGnK+VlCmRX+bM=,tag:iti10WLJTlvaYb3Y99pzxw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
