apiVersion: v1
kind: Secret
metadata:
    name: ghcr-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:2A4xf/yeTZw=,iv:NKyCpHd+DMpZXCgQH4caFmqybitMh5eqFoV+Jz0WK1c=,tag:vhQ/DWSzJGOAQhLIXDJGmA==,type:str]
    password: ENC[AES256_GCM,data:Jpe5Vwood5IwQcn+dFG7,iv:7RtP8Bc69N3pQ3hGnwnU4M1ZcUDbjy5oV+aqEe/i5yg=,tag:H510Fm4AkBGa1bH9TGYW2g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQ1VVS2VvYmdyeDQxOUgx
            U3kxZVJ3N1pYT05ueWIyL3lKSkR0cU1HMmkwCmNsS0hwODBjWmYyWlROdW16VWll
            NFViMSsvc09TRkpOcXJvQitmNjhqTG8KLS0tIDR1akJJUmtOQjJDNm4zZERIQnB3
            RG55TER1SmJxUlFPSWdqbzcydjZoY3cKybnnhIH78bGPw102llE1cZhJI3oU1CBT
            N9YaxxtUiY+TjuTtY+z+Y/3WJqFWJCeQ1dysxk44PkvtPIhxLuSFzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T02:44:54Z"
    mac: ENC[AES256_GCM,data:TWcqeYyq8FR6RSLHF/Xj1noV82vB9x1200sDrNEL/0jzn05HjsjDaKwHPOsRjKQEt1avVD2ITlTTq2H8BPxQhbuExGpUEk0dlwA6DOpDi3Mz5vFDwrN5RJHVHdZ+hml8QPmH6m0zquYUt4oV7A74RpfLRcZZW+KIElxcLr/sG0U=,iv:JtSFZ+pWDephKnKMlWcONfmQoPrSFNqk3U8malmYsuk=,tag:M8NZkaUH3ZyjufJ1oNNnVw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
