apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:GcT/cr2Bym+BHMM1A7JpDxREpJJyWtmD+aPaNr6hviEssXYdKGum9DDg+VXk8fQw4V26eFdk0gxwmeGsv6GhhA==,iv:movSP5reBNurJun7vg52kCSpHoE69Rm5ZrJOLVDfJ3w=,tag:8P0Lof9lsxJAUsNxTXFhPA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WkVPVXJxRmFFa0Q5MFZE
            QUJPcHBXOUtTZDJMbDFuOEw5UHV3RXU4eEZBClBGUmxRZUFLL09wNys1MlFnQ3Nv
            bEwyTnVtZ2xlbmE1Umo2R1pDYjc5eDAKLS0tIFhvYVQvYVZUbEY3ODNnKzdnOEU2
            NHpDMTQwOGpFK01oRldBeW53Q3VBRVUKvLMsY5nzHCLGrGqTrHjbBiXXjs9szBDd
            /8obEhJSnySjBPrRXToPhHp8EYratWcFNAgjUurD2/xF4QnpXpQFEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T18:01:17Z"
    mac: ENC[AES256_GCM,data:PjOJlxv+5MT3ue0lS1nlk2OhHiVw4kZRbyWldoFOiR5L1fo0Us/Sd48rv/xWPWz+56Og/Qirm4W8TiKpcNQuAXRH6CtP0AYZcfbJHE1d/9sRM22DcnFdVbRw0tb3aXD+hEcDyRM98qIM2gUlgKDyJvqcZZ0wJRGWaalZamv5E7o=,iv:FdIVhcGm+LBfJHCdaUWEf53GK7bTcL7k5ZMOKu72mHo=,tag:Iffl3KkHwF+2gbREPa0Cgw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
