apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:1DFWFnAms0DsxdWVCrglQw/OvW3Ja1vrdhrxyoQqlxgefe5ClgpXRphUvYSMcsPYb1BeKRx/XjV4XKzLopqeyA==,iv:4EZBHOi6wqp6498GNLCpbClTSOG1ZxmDxZGu5nn2OEA=,tag:hhMDY1IJg55SZEhLhFmn1A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBseERhOVVQWnlnekticG1C
            UXpRaVJXQ1JkUjZUT2tsMVMzQkRMR1ZlcUcwClJrbFhnOXB2ZVpHaitDLzRpdmJS
            aWJQQm04ZXEvZ09SV3hVMFN0S0NmdGcKLS0tIDFoT3VDWEluNUdDWlZ6SnRiL2Fq
            NTNmaHVkUDFlUGROdkZHRzRkRzVaalkKRjC8wypsnuVxYVmkYhDYoFGP1UmRF7X8
            U554lzljahrzhjRwDV902SJS7CRgHf0ynBy7X746CWkpFmNwnd1dVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T02:26:00Z"
    mac: ENC[AES256_GCM,data:z7gcL5ZFD0q9fDLT03XvUZ2WNRlZi3rybHAAF50FCco79ZlCmUIYESxB5UWauZeHxIrat8jbRECRDafe1/OytX59Ui4j8abSJjyljBYMIwmXoEaGdREl/IkIxksPJjzMrdH38IiLhpI9dzuc6N1QMbWcsX/67IGW3I59rDXDZeY=,iv:ToQoGtN+t9rcjhrUYAjaf09d2kFZxdrsY+PpWsokdQc=,tag:l4y3C5Y+vMlDasv8MgZd6w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
