apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:GhscfhCD/PDMz/6KukBSNfYbbJlJIEmiiFa/T8PC3m2CVsYgMx1lfU88EiLqq8ZBOwW0Sld69JE3qIMEPu25lg==,iv:3V6zxVrLtWVpDXR3nxN9kAtVQtOX8U/8Mwluz2rHbQ4=,tag:iPzbju7L2Uteu7mndltHrA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNblBDWkNuTDR2U0dTWlRl
            ZjdxUjU1L1lLTnlJVy9hSk1VMFdDelNsd1c0CmdLSEk5ZDU0MlhhZmMzVFcrNFFi
            cU4xRDIzbHZuVWh6Mlg0ek51TVBKWXcKLS0tICtOdzJHMVNYNHY4bThZTFJEM1d5
            Z21MaHI5SnV2K0cvT0FpMS8rOUNzNDAKZtbAUBvJu+z+K/qUKswd54ZcKVWjC/9o
            numhyUIUGlyE7sHO2A9NU5ZH4iat1aTB9URE9/2X3FgU0BdXOa3Sgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T02:35:57Z"
    mac: ENC[AES256_GCM,data:c+Nyu57Zw8p8JS1M3As9SlGhigsmGTZDjPoMXeHiDRp9gx/+R9HSfBk9rOKnaxsQWC8CDTuEE/LodSpN6eP3CM6UZhepd3+Oy1X7K7LlIt181Fe9JfERwsnEMW7XXV2K6Jruf25jVBiTnH3T/kh0r09JPu7ER8a9DK9bkdMbfmA=,iv:+hHVhSktIxPjIpH67wdQJHtx5WbK0BTFAtZ8uuVjk8U=,tag:THT84BrnDVrcRifmj3/NRg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
