apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:3b/WpO4lXHaf3T4SMeHyo9WroIwMfyWKNfwonTx9Kh2pwpCeAV+LRCtwQTp9Mq7nQEZvWyGEDF+R44YLJQkvSA==,iv:6jxeah8WMo6dWnW4vc7iSg6PzeJ0xIcISlsyD1KCui4=,tag:zxLakxqj2M0VR4Ah2ZEspA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcHh1bTJJZmFSZE5oVkc0
            a0x4YW0xc3BCS09ucVpWNTBzNGpJQkpXT2lrCnJ0VzVKcUtVVTA1ekZCSnQ4Njhi
            T1dzSnkvWXlya0pVR3Z2SmJFRTFNQVEKLS0tIDNQN3hNQjNrU0NEeng0ZVdrMjF1
            V29ndWFtR1I1M0ljUml5NDV1dGdQUVUK0Ye7oqw1VI1//UkhbUdNYujJ9J9plLrj
            5G2YW6IBnX1RMiMktp/xRSaLmaV9Dg3okt8/2rxFriYFrMcm4B/uAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T02:18:02Z"
    mac: ENC[AES256_GCM,data:lDtD3wqUwgHaX3JEk11v+8cnQiFxQMjCCDSa+SuumKMHoW6zl0BL8af5eNWcl5tq4sOFdPN+x1HV9PFGhC1jrmLQOVWquGx4wUlhm6VDMPw4atsSU214bhlWkRELAxNefK4BWTV39RtIpY/72Vk/5cvUbupyWTCbil+WqPxNzo8=,iv:PqJzUDmgFGhrzZ9eUq/ZBNuO/rZRYpZ9GDfxvxzDzNU=,tag:WaeRpxTgvMugqa9ddZbqqw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
