apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:vz5X7+3l+nIS8hWvit7a1hGSRa0l0vuimZhXJY7FavoQvSAHp+TciaiJgaiWAY0r4ZClUYebpggzvlpP//bX9g==,iv:gL4MeOIKSCUMLLAG3bMGcpK87K5RVi35FRnFeuAk8kQ=,tag:rfIDRNkEcuSOqVqkqvPheQ==,type:str]
sops:
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0OTQ0OGI2T3FGWWF4clZB
            Smg2UHZydDZGQkdYWGdnVjNEVjFpT1lSemtRCmxTeWp2aFRUSTMwZlZ4Q2VrZzBX
            Rk13WVliV2hVSHExdlNZK0krdTkwVFUKLS0tIERTL21iYUpQNkxkZC80MFRpcm1j
            eWkyZGNqYlZrN2ZCZ29PVmhXa29CZ0UK3p4BBT2QIIGS49m+iQd1p5ed6mmdYskn
            l4zlfVrX1GyGGBzWZMyu9ubzZj+Zpl8P6CgCvORlM1GkeOxbAmKm6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T22:16:32Z"
    mac: ENC[AES256_GCM,data:EQDa+cc42CJpcGNvruXmAyRZMF7UQmTzLC1AHCraQWG9jG+8RmYbr3YrD0akQ3lyLIR2whuFL51QQnQ3m76v15rvo0g7cYFDpFv7rFougAqZPh2Tl9zc78ecGI6NhwpwLTzindkzaqIE0TeRY7TbBd+yTSXH9Eh1TAhvd3PlDzk=,iv:Vw2Vx+513MhhTCeTlfiiqguPU7ascESuU0aLGMPyTnM=,tag:p1POGG7r/Eck+Xf6xGkKHw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
