apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:GXQ8iAV5K6bSXSkUqblz6GUECgjlkAi4UjOkOC0D5FUH5diYS7hD4rlBC9Ios6BkanecxOLACMlrKRjA2V9h4g==,iv:w5bvgGZLkr4fQlYR8P/Ad/C/gWzAm0PgpLZqrMv0yi8=,tag:UHDSs0Ht4AtlxII2Hkdf5w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOEw1bko3MzNRbktmTzdl
            QVZtWnY5czZ3bzJDcEdTdVZESXBZdEUwTjF3ClhzYStOdS9jMnNyRjJTYSszVFVa
            TlJ0RjkxcU9Ed3lJdmFRSDJRUG9mem8KLS0tIDgwY3FibWE5dWRLYS95ZVBkakVs
            SFFrenhvQVdjbTVmL2xSb1BRWk5yRDQKrqxs+bHJuqDAIcwi/rZAgDmGuB2vgLZ5
            CoqdHiwvkfAlSD/74OyHBqNSWIPpHuFnIYYd4GNmKn6jTvAv/MHHZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T22:22:43Z"
    mac: ENC[AES256_GCM,data:iuhODp4jc4yQNj7MSmlUB6Pdb0M0BRGCn9S5UjS13FZLyOje3x7rSKL2fg3a1lSAt3sQZc46J4IQnNeiyY8zkQmuauqbbJxpFEG3BLUylimDPNQyGoBlDRtGpBqiMjj0wcAfWcN8iQ5E8X/H/OriLcKaukjEK8bojMqZPctk4aA=,iv:70zLNBrIQVhfL1TnD4k3FqrNLZuOpX5BjP72AcmzTnA=,tag:O3OfZwZToHXMZZgnHhDp+A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
