apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:4M9pGk2k50WVQRRb+vOscSw7FBOUDj8pqQUFpNlDhA6yFypIruZif9q8ZF6jtC8Q6CQ8KF1JWgSPyxRK9CybEQ==,iv:HT3GvIktJYZQPUfC3TuHCM+t4+fX8WiRhbd5T0aUny8=,tag:+krDdeEIIfMLEDKWlXTsFA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MzhPZlBkcjl5ZmxZcHN1
            d2h3UkFDeHg4MHJtQ0lpajJTU0ttK1ErWGlFCjZKR29YSVp3WVJTaENNQUpQQS9q
            U0F1N2xOZVVDOTI3bTlJLzc4RllqaDQKLS0tIDBPTjE0dERYNlZPZUp4dExrSVdn
            S3BXZkk3d3lvVldaOTMza3ZhNEhEUmcKoGdXpqR1uerEMRq1cMJ0QzX8o6Qy7FDt
            6l3XVB4VlXKYwx1JlKV5mKEWrXxNZqwlSmzqv0+pxoDiOcZF7BgzlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T02:44:54Z"
    mac: ENC[AES256_GCM,data:eCYqX4YgUrcVk56rM67GoySbD8di0adY0rPTQ3tKd47YVlyLR85ekkONR9aL1l4nn1cLJZ1gCz5xkgTspP5GMklfNK99fL7V2tF/KlItXLIACKgryAhUbtAvTfox67VDWOedp4KcpHdEunFLFBiNn/U23XdukEluaAC3OBupmkw=,iv:gSEjzK4Q/RjMnCD45vQSPw/SHXCWYopyavRQlyGYYn4=,tag:Unn9OKGAuHgPgv3qTtmEaQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
