apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:Hcjy6fB6/dkECSnEdpshDGfEGqiTy4B2TRDyXPbOLu9bxj17bKVXAInOlaeJHbhLFgf5Xm+tlrrK3N55cZTXmw==,iv:ZF7ygA4244fyfI12WcWnE/NJi4c9ZByixsIGDzvhEHs=,tag:piDyQ6llZErSh39rM+EBwA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiR045RVl1WDRBMzExam1q
            VFQwYkhZZEpodi80TFpHT2JNZ3I1SlZnNERBCjE3WVFsajJxUE9LMmNUZmNURWFi
            dUNka2hnRG01NzVGakpYSlVQV3RzZjgKLS0tIHE1aCtVZGpDUHFwaEl5L0IzVm4r
            dStIZkFlazRDUElhZnpheVZiNTRTTk0KPDmoD813Tm7d0YNzGmBbkBK7wGDAzAi8
            Gtad3C31k0UZ0GQeVGuT9Y7a0C7w+BIrE03u60HRlfmvJ8zvLsfvLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T21:10:54Z"
    mac: ENC[AES256_GCM,data:lkV0eZbkh4w1BvIAPKbsg+SPL3j+ulbksu/iK/y6DF8n6ew3/X+QqA86PgMSZyfOvMpLEP7k61p42fyqHwDdY8gnA9E21nHQ5hgpSF3+Vyb+089vgsFClE5Rbt0VpXody2/gohnOeREBltUtr66TtgTncnOGNiotk51sl0D/Oy0=,iv:ZIAzRUOiQxmm7nEdoEiyFHMCqhXRZxO5IdWZibuYoqA=,tag:/LlCbdqtQcCGA4ecVgO3Tg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
