apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:8mInL/xbUpVfilGY2CTLhLtUkcXNGlycgHLvXsYBlpXrD1wEGWqCLRa/N/yHrEDbXmGLSUVHAzx4vM0qXM+5nQ==,iv:UV1NUdN5NV4xvbAcna4vdpdc1LXquTsSc3ByAlFOL+Q=,tag:LgCHFk7eQ7y74RJc+soXNQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xuryc2afg7fh6tg2d85mydr05rh93xf8dhrcq4xata7ec33t8uvs6kl3yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSStpNUpKOEZmNFhzU1Z5
            YTQ1bHA2M2RmckZMVUFLMkw0R1pwK3FxWGtZCnpKQnZhUTJocnUyUDU5S1BWS2ZP
            cWI3Y1puQit6NFBXeWdRd2NKb0x6SmMKLS0tIDZSOThlYjdyVFgwUmdmZGlkSHVT
            b09LZWFGWHc3cm1DQk9ERHB6Yk4xTVkK0CpFN6P2mV7RVZthxYQ9Fi0Kg62lOw3g
            b2GLBCd5iAxtRH3eASJneLhss3c/Vx9FewvISFRDGGU6nLRSdqrUkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T20:36:09Z"
    mac: ENC[AES256_GCM,data:Ll0faJgjK6o1ORaa1REG2DrTyp99YohUch77+e0IjtheYU4bFJc7Oj9rByrXNcUPt8M9xIxLvJN7bFudUZiP9Ll39Y+aZClUAZrsSceYdWzq/rMq7ZxzK2KMenY3+ajUDxNc8FOL7X7/TVr6dkUJPXCYMhR1lxkZceNrIuNlQ+w=,iv:I2hz9oYuDsyhHfX5wiw0lrz6roUcpBTLznAeMeN0f7U=,tag:UEfrCA7JOdvF2qQ00wQRFw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
