apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  #- downloads-nfs-pvc.yaml
  #- media-nfs-pvc.yaml
  - roon/ks.yaml
  - prowlarr/ks.yaml
  - radarr/ks.yaml
  - lidarr/ks.yaml
  - lidarr-flac/ks.yaml
  - lidarr-liz/ks.yaml
  - nzbget/ks.yaml
  - overseerr/ks.yaml
  - sabnzbd/ks.yaml
  - sonarr/ks.yaml
  - tinymediamanager/ks.yaml
  - plex/ks.yaml
  - emby/ks.yaml
  - tautulli/ks.yaml
  - notifiarr/ks.yaml
  - recyclarr/ks.yaml
  - readarr/ks.yaml
  - mylar/ks.yaml
  - calibre/ks.yaml
  - calibre-web/ks.yaml
  - bazarr/ks.yaml
  - doplarr/ks.yaml
  - kapowarr/ks.yaml
  - tdarr/ks.yaml
  - dizquetv/ks.yaml
  - tunarr/ks.yaml
  - deluge/ks.yaml
  - flaresolverr/ks.yaml
